import type { ConceptHub } from "@/lib/concept-hubs";

export const fiveAggregatesGlobalSelectionAliases = [
  "五蕴",
  "五蘊",
  "五阴",
  "五陰",
  "五众",
  "五眾",
  "五聚",
  "五取蕴",
  "五取蘊",
  "色受想行识",
  "色受想行識",
  "色、受、想、行、识",
  "色、受、想、行、識",
  "pañcakkhandhā",
  "pañcakkhandha",
  "pañcupādānakkhandhā",
  "pañcupādānakkhandha",
  "pañcupadanakkhandha",
  "pancupadanakkhandha",
  "five aggregates",
  "five clinging aggregates",
] as const;

const sn2248Path = "/jingzang/samyutta-nikaya-sn22/048-sn22-48-0001-0021";
const sn2279Path = "/jingzang/samyutta-nikaya-sn22/079-sn22-79-0001-0120";
const t0102Path = "/jingzang/taisho-t0102/001-0499c";

export const fiveAggregatesDefinitionSourceHrefs = [
  "/jingzang/xinjing/001-0848c#T0251.001.0848c06",
  ...[
    "T0102.001.0499c10",
    "T0102.001.0499c11",
    "T0102.001.0499c12",
    "T0102.001.0499c13",
    "T0102.001.0499c14",
    "T0102.001.0499c15",
    "T0102.001.0499c16",
    "T0102.001.0499c17",
    "T0102.001.0499c18",
    "T0102.001.0499c19",
    "T0102.001.0499c20",
    "T0102.001.0499c21",
    "T0102.001.0499c22",
    "T0102.001.0499c23",
  ].map((segmentId) => `${t0102Path}#${segmentId}`),
  ...[
    "sn22.48:1.2",
    "sn22.48:1.4",
    "sn22.48:1.5",
    "sn22.48:1.6",
    "sn22.48:1.7",
    "sn22.48:1.8",
    "sn22.48:1.9",
    "sn22.48:1.10",
    "sn22.48:2.1",
    "sn22.48:2.2",
    "sn22.48:2.3",
    "sn22.48:2.4",
    "sn22.48:2.5",
    "sn22.48:2.6",
    "sn22.48:2.7",
  ].map((segmentId) => `${sn2248Path}#${segmentId}`),
  ...[
    "sn22.79:2.1",
    "sn22.79:2.2",
    "sn22.79:2.3",
    "sn22.79:2.4",
    "sn22.79:2.5",
    "sn22.79:3.1",
    "sn22.79:3.2",
    "sn22.79:3.3",
    "sn22.79:3.4",
    "sn22.79:3.5",
    "sn22.79:4.1",
    "sn22.79:4.2",
    "sn22.79:4.3",
    "sn22.79:4.4",
    "sn22.79:4.5",
    "sn22.79:5.1",
    "sn22.79:5.2",
    "sn22.79:5.3",
    "sn22.79:5.4",
    "sn22.79:5.5",
    "sn22.79:6.1",
    "sn22.79:6.2",
    "sn22.79:6.3",
    "sn22.79:6.4",
    "sn22.79:6.5",
  ].map((segmentId) => `${sn2279Path}#${segmentId}`),
];

export const fiveAggregatesConceptHub = {
  entry: {
    slug: "wuyun",
    title: "五蕴",
    href: "/gainian/wuyun",
    summary: "从《心经》、T0102 与巴利《相应部》分清色、受、想、行、识，并保留“蕴／取蕴”的原典边界。",
    aliases: [
      ...fiveAggregatesGlobalSelectionAliases,
      "五蕴是什么",
      "五蘊是什麼",
      "心经中的五蕴",
      "心經中的五蘊",
    ],
    selectionAliases: [...fiveAggregatesGlobalSelectionAliases],
    selectionSourceHrefs: fiveAggregatesDefinitionSourceHrefs,
    prompt: "《心经》中的五蕴是什么？",
  },
  metadataTitle: "五蕴｜色受想行识原典导读",
  description: "从《心经》《佛说五蘊皆空经》与巴利《相应部》理解色、受、想、行、识，辨明五蕴与五取蕴，并回到稳定原典段落。",
  about: ["五蕴", "五取蕴", "色受想行识", "心经", "相应部", "pañcakkhandhā"],
  termCode: "wuyun",
  heading: "五蕴",
  sectionTitle: "五组观察范围",
  sectionDescription: "先辨认经验正在以什么方式发生，再问它是否恒常、可控，或应被执作“我”。",
  hero: {
    eyebrow: "概念 HUB · 五组经验原典导读",
    highlight: "五蕴",
    beforeBreak: "，不是五个",
    afterBreak: "藏在身体里的灵魂部件。",
    lead:
      "色、受、想、行、识，是佛典反复用来观察身心经验的五组范围。《心经》从“照见五蕴皆空”进入离苦；巴利《相应部》则分别列名、说明活动，并把“五蕴”与“五取蕴”分开陈述。先看清这五组正在怎样发生，才不会把名相背诵误当成观照。",
    primaryActionLabel: "查看五组原典",
    primaryActionHref: "#evidence",
    secondaryActionLabel: "继续问经",
    secondaryActionHref: "/wenjing",
    lensNotes: [
      { label: "经验范围", text: "色 · 受 · 想 · 行 · 识" },
      { label: "研究边界", text: "蕴不直接等同于取蕴" },
      { label: "般若入口", text: "照见，而非删除经验" },
    ],
  },
  stats: [
    { label: "可定位证据", value: "5 处" },
    { label: "观察范围", value: "5 组" },
    { label: "原典语言", value: "汉文 · 巴利文" },
    { label: "严格平行认定", value: "0 项" },
  ],
  termsHeading: "先别急着背名相：每一蕴在经验中做什么？",
  termsIntro: "下列中文是帮助进入原文的最低限度导航，不把古典术语强行等同于现代心理学模块，也不把五组拼成一个固定自我。",
  terms: [
    {
      label: "01 · rūpa",
      heading: "色",
      detail: "身体与物质形态这一组。SN 22.79 以会受冷、热、饥、渴等影响说明 rūpa；它不只是眼睛所见的颜色，也不是一个不变的身体实体。",
    },
    {
      label: "02 · vedanā",
      heading: "受",
      detail: "经验的感受调性。SN 22.79 列出乐、苦、不苦不乐；这里的“受”不是把一段复杂情绪故事全部装进同一个词。",
    },
    {
      label: "03 · saññā",
      heading: "想",
      detail: "辨认与标记所缘的活动。原文以辨认青、黄、红、白为例；它比日常中文“胡思乱想”更窄，也不能直接等同于全部思维。",
    },
    {
      label: "04 · saṅkhārā",
      heading: "行",
      detail: "造作、构成与推动经验的活动。SN 22.79 用 abhisaṅkharonti 说明其造作面；“行”不能只译成外在行为，也不宜当成神秘实体。",
    },
    {
      label: "05 · viññāṇa",
      heading: "识",
      detail: "对所缘的识知活动。原文以识别酸、苦、辛、甜等味为例；这里不支持把“识”说成独立常住、在五蕴之外指挥一切的灵魂。",
    },
  ],
  boundariesHeading: "同样列出五项，也要保留三种文本任务。",
  boundariesIntro: "五项名目可以互相导航，但“分类经验”“观察无常无我”与“照见皆空”不是一条无需论证就能互换的句子。",
  traditions: [
    {
      label: "巴利《蕴相应》",
      term: "pañcakkhandhā · pañcupādānakkhandhā",
      supported: "SN 22.48 分别说明五蕴与五取蕴；SN 22.79 以受影响、感受、辨认、造作、识知等动词帮助进入五项。",
      boundary: "本站中文只作工作释义；词源式说明不是现代心理学定义，也不能据单一经段穷尽上座部后世论书的蕴论。",
      sources: "SN 22.48 · SN 22.79",
    },
    {
      label: "汉译 T0102 语境",
      term: "五蘊 · 五取蘊",
      supported: "经文把色及受想行识置于不可随欲支配、无常、苦、无我与无我所的观察次第中，并明说“觀此五取蘊”。",
      boundary: "本页不因结构相近就宣称 T0102 与某一巴利经已经完成严格平行审定，也不以网页摘要取代完整行段。",
      sources: "T0102.001.0499c10–27",
    },
    {
      label: "汉译般若语境",
      term: "照見五蘊皆空",
      supported: "《心经》把五蕴、观照、般若与度苦放在同一句中，随后从色展开到受想行识“亦复如是”。",
      boundary: "“皆空”不等于五组经验停止显现；本页也不以一句短经裁决中观、唯识、禅等传统的全部解释。",
      sources: "T0251.001.0848c06–09",
    },
  ],
  evidence: [
    {
      kind: "直接证据",
      canon: "《般若波罗蜜多心经》T0251",
      title: "《心经》从五蕴的观照进入离苦",
      quote: "觀自在菩薩行深般若波羅蜜多時，照見五蘊皆空，度一切苦厄。",
      reading: "最小可证结论：原句把行深般若、照见五蕴与度苦放在连续关系中，并不是一张要把经验删除的清单。",
      locator: "T0251.001.0848c06–07",
      href: "/jingzang/xinjing/001-0848c#T0251.001.0848c06",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0251_001",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 22.48",
      title: "五蕴的五个名目",
      quote: "Katame ca, bhikkhave, pañcakkhandhā? … rūpakkhandho … vedanā … saññā … saṅkhārā … viññāṇakkhandho. Ime vuccanti, bhikkhave, pañcakkhandhā.",
      reading: "工作释义：何为五蕴？经文依次列出色、受、想、行、识。省略号标示原文对过去未来现在、内外、粗细等范围的重复展开。",
      locator: "sn22.48:1.4–1.10",
      href: `${sn2248Path}#sn22.48:1.4`,
      sourceUrl: "https://suttacentral.net/sn22.48/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 22.48",
      title: "五蕴与五取蕴在同一经中分开陈述",
      quote: "Pañca, bhikkhave, khandhe desessāmi, pañcupādānakkhandhe ca. … Katame ca, bhikkhave, pañcupādānakkhandhā?",
      reading: "工作释义：本经先宣布将说五蕴与五取蕴，再分别设问。五取蕴段反复出现 sāsava、upādāniya；研究时不能悄悄删掉“取”字。",
      locator: "sn22.48:1.2 · 2.1–2.7",
      href: `${sn2248Path}#sn22.48:1.2`,
      sourceUrl: "https://suttacentral.net/sn22.48/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 22.79",
      title: "用五种活动进入五项，而不是把它们物化",
      quote: "Ruppatīti … rūpaṁ. Vedayatīti … vedanā. Sañjānātīti … saññā. Saṅkhatamabhisaṅkharontīti … saṅkhārā. Vijānātīti … viññāṇaṁ.",
      reading: "工作释义：色会受影响，受在感受，想在辨认，行在造作，识在识知。这里只保留原文的动作线索，不把它们冒充现代学科的完整定义。",
      locator: "sn22.79:2.1–6.5",
      href: `${sn2279Path}#sn22.79:2.1`,
      sourceUrl: "https://suttacentral.net/sn22.79/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "《佛说五蘊皆空经》T0102",
      title: "五蕴观察进入无常、苦与非我",
      quote: "色為是常？為是無常？……色是無常。……應知受想行識，常與無常，亦復如是。……觀此五取蘊，知無有我及以我所。",
      reading: "经文不是只给五项下定义，而是要求以正智观察其无常与不可执为我、我所；五项因此是修行中的观察范围。",
      locator: "T0102.001.0499c14–23",
      href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c14",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0102_001",
      language: "zh-Hant",
    },
  ],
  translationNote: "巴利文下方中文均为本站工作释义；跨语种材料只作相关结构并读，当前没有双人复核结论支持严格平行经认定。",
  misreadingsHeading: "先拆掉四种会妨碍观照的误读。",
  misreadingsIntro: "五蕴的价值不在于多背五个词，而在于阻止我们把流动经验重新拼成一个固定、可完全支配的实体。",
  misconceptions: [
    {
      myth: "五蕴 = 五个灵魂部件",
      correction: "证据不支持。现有经文把它们作为会受影响、感受、辨认、造作与识知的观察范围，并继续检查其无常、非我与执取。",
    },
    {
      myth: "想 = 所有想法，行 = 走路做事",
      correction: "过窄。SN 22.79 以 sañjānāti 说明“想”的辨认面，以 abhisaṅkharonti 说明“行”的造作面；日常汉字不能直接代替原文范围。",
    },
    {
      myth: "五蕴与五取蕴完全同义",
      correction: "不能这样省略。SN 22.48 在同一经中把 pañcakkhandhā 与 pañcupādānakkhandhā 分别设问、分别说明；比较时必须保留“取”。",
    },
    {
      myth: "五蕴皆空 = 身心经验根本不存在",
      correction: "《心经》写的是在般若中“照见”并由此度苦，随后仍逐项谈色受想行识；当前证据不支持把“空”改写成经验从未发生。",
    },
  ],
  readingHeading: "从《心经》的问题出发，再把五项逐层拆开。",
  readingIntro: "这条路径让入门者先抓住问题，让修学者得到观察顺序，也让研究者核对巴利复合词与稳定段落。",
  readingPath: [
    {
      step: "先看问题",
      title: "《心经》：照见五蕴皆空，度一切苦厄",
      text: "先看五蕴为何出现在般若与离苦的语境，不要一开始就把它读成脱离修行目标的分类表。",
      href: "/jingzang/xinjing/001-0848c#T0251.001.0848c06",
    },
    {
      step: "核对名目",
      title: "SN 22.48：五蕴是哪五项",
      text: "沿段落逐项核对色、受、想、行、识，以及每项覆盖过去未来现在、内外、粗细等范围。",
      href: `${sn2248Path}#sn22.48:1.4`,
    },
    {
      step: "分清取著",
      title: "SN 22.48：五蕴与五取蕴分别设问",
      text: "继续读同一短经的后半，观察“取”如何改变术语，不把两个复合词草率合并。",
      href: `${sn2248Path}#sn22.48:2.1`,
    },
    {
      step: "观察活动",
      title: "SN 22.79：受影响、感受、辨认、造作、识知",
      text: "用原文动词把五项带回当下经验，同时记住这些线索不等于现代心理学的最终定义。",
      href: `${sn2279Path}#sn22.79:2.1`,
    },
    {
      step: "回到修行",
      title: "T0102：从无常检查我与我所",
      text: "最后沿汉译经文看五蕴为何不是可随欲支配的我，并把观察落在执取的松动上。",
      href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c10",
    },
  ],
  footerNote: "本页只综合 foxue.ai 当前受控的 T0251、T0102、SN 22.48 与 SN 22.79。它不把汉巴材料判作已审定的严格平行经，不代替阿毘达磨、般若论典、宗派注疏或具资格的修习指导。",
  updatedAt: "2026-09-15",
  footerActionLabel: "带着五组经验继续问",
  footerActionHref: "/wenjing",
  related: ["kong", "wuwo", "wuchang", "guanxin"],
} as const satisfies ConceptHub;
