import type { ConceptHub } from "@/lib/concept-hubs";

const sn366Path = "/jingzang/samyutta-nikaya-sn36/006-sn36-6-0001-0063";
const sn3814Path = "/jingzang/samyutta-nikaya-sn38/014-sn38-14-0001-0017";
const sn5611Path = "/jingzang/samyutta-nikaya-sn56/011-sn56-11-0001-0060";

export const sufferingSourceHrefs = [
  ...[
    "sn38.14:1.1",
    "sn38.14:1.2",
    "sn38.14:1.3",
    "sn38.14:1.4",
    "sn38.14:1.5",
    "sn38.14:1.6",
    "sn38.14:1.7",
    "sn38.14:1.8",
    "sn38.14:1.9",
    "sn38.14:1.10",
    "sn38.14:1.11",
  ].map((segmentId) => `${sn3814Path}#${segmentId}`),
  ...[
    "sn36.6:1.5",
    "sn36.6:1.6",
    "sn36.6:1.7",
    "sn36.6:1.8",
    "sn36.6:1.9",
    "sn36.6:1.10",
    "sn36.6:2.1",
    "sn36.6:2.2",
    "sn36.6:2.3",
    "sn36.6:3.1",
    "sn36.6:3.2",
    "sn36.6:3.3",
    "sn36.6:3.4",
    "sn36.6:3.5",
    "sn36.6:3.6",
  ].map((segmentId) => `${sn366Path}#${segmentId}`),
];

export const sufferingConceptHub = {
  entry: {
    slug: "ku",
    title: "苦",
    href: "/gainian/ku",
    summary: "从《杂阿含经》与巴利《相应部》分清苦谛、三种苦与第二支箭；苦是应被遍知和止息的问题，不是对人生的悲观总判决。",
    aliases: [
      "苦谛",
      "苦諦",
      "苦是什么",
      "苦是什麼",
      "人生是苦",
      "一切皆苦",
      "三苦",
      "第二支箭",
      "两支箭",
      "兩支箭",
      "苦不是悲观",
      "苦不是悲觀",
      "佛教为什么说人生是苦",
      "佛教為什麼說人生是苦",
      "dukkhatā",
      "dukkhata",
      "three kinds of dukkha",
      "three kinds of suffering",
      "second arrow buddhism",
    ],
    wordAliases: ["dukkha"],
    selectionAliases: [
      "苦谛",
      "苦諦",
      "三苦",
      "第二支箭",
      "兩支箭",
      "两支箭",
      "dukkhadukkhatā",
      "saṅkhāradukkhatā",
      "vipariṇāmadukkhatā",
      "dukkhadukkhata",
      "sankharadukkhata",
      "viparinamadukkhata",
      "dvisallena vedanaṁ",
      "dve vedanā vedayati",
    ],
    selectionSourceHrefs: sufferingSourceHrefs,
    prompt: "佛教说“苦”，是在否定人生吗？",
  },
  metadataTitle: "苦｜dukkha、三苦与第二支箭原典导读",
  description: "从《杂阿含经》与巴利《相应部》理解苦谛、三种苦及第二支箭，辨清 dukkha 不等于悲观主义，并回到稳定原典段落。",
  about: ["苦", "苦谛", "三苦", "第二支箭", "杂阿含经", "相应部", "dukkha"],
  termCode: "ku",
  heading: "苦",
  sectionTitle: "诊断范围",
  sectionDescription: "先辨认哪一种不安稳正在发生，再看它的条件、可止息处与可实践道路。",
  hero: {
    eyebrow: "概念 HUB · 苦的原典诊断图",
    highlight: "苦",
    beforeBreak: "，不是对人生的",
    afterBreak: "悲观总判决。",
    lead:
      "佛典中的 dukkha 不能被一个现代汉语词完全包办。SN 56.11 从生老病死、怨憎会、爱别离、求不得与五取蕴界定苦谛；SN 38.14 又列苦苦、行苦、坏苦所对应的三类 dukkhatā。经文不是让人相信“一切时刻都很痛”，而是训练人如实辨认、遍知，并走向止息。",
    primaryActionLabel: "打开诊断证据",
    primaryActionHref: "#evidence",
    secondaryActionLabel: "带着处境问经",
    secondaryActionHref: "/wenjing",
    lensNotes: [
      { label: "范围", text: "苦苦 · 行苦 · 坏苦" },
      { label: "任务", text: "应知 · 应遍知" },
      { label: "实践", text: "不再补上第二支箭" },
    ],
  },
  stats: [
    { label: "可定位证据", value: "4 处" },
    { label: "苦的类型", value: "3 类" },
    { label: "原典语言", value: "汉文 · 巴利文" },
    { label: "严格平行认定", value: "0 项" },
  ],
  termsHeading: "先拆开四个层次，才不会把“苦”说窄。",
  termsIntro: "下列中文是进入原文的导航：它帮助分辨语义范围，却不声称一个译词可以穷尽 dukkha，也不把后世论释全部倒灌进短经。",
  terms: [
    {
      label: "译词边界",
      heading: "dukkha",
      detail: "可涉及直接痛苦、不稳定、受条件支配与不能恒常满足等层面。把它只译成“疼痛”会太窄，把它扩成“一切都毫无意义”又越过了原文。",
    },
    {
      label: "第一圣谛",
      heading: "应遍知",
      detail: "SN 56.11 先列苦谛的范围，随后说它应被遍知。这里要求的是辨认与理解，不是把“人生是苦”当成必须接受的悲观口号。",
    },
    {
      label: "三种 dukkhatā",
      heading: "苦苦 · 行苦 · 坏苦",
      detail: "SN 38.14 原次序为 dukkha、saṅkhāra、vipariṇāma 三类。常见汉译名只作术语导航；三者不是轻、中、重三个疼痛等级。",
    },
    {
      label: "感受与反应",
      heading: "第一箭 · 第二箭",
      detail: "SN 36.6 区分身体苦受与随之而来的心理反应。它不是说病痛可以靠意志取消，也不能用来责怪创伤者“选择了第二箭”。",
    },
  ],
  boundariesHeading: "同一个“苦”字，至少要守住三条边界。",
  boundariesIntro: "经文可以互相照明，但文本身份、术语层次与现实照护不能因此被抹平。",
  traditions: [
    {
      label: "汉译《杂阿含经》",
      term: "苦圣谛当知、当解",
      supported: "现有段落直接支持苦谛是一项应知解的任务，并把它与集当断、灭当证、道当修置于完整结构中。",
      boundary: "本页不凭这一段重建全部汉译阿含的苦论，也不把“当知、当解”自动等同于某一后世论书的技术定义。",
      sources: "T0099.015.0104b15–18",
    },
    {
      label: "巴利《相应部》",
      term: "dukkha · dukkhatā",
      supported: "SN 56.11 界定苦谛范围，SN 38.14 明列三种 dukkhatā，SN 36.6 用两箭说明苦受与反应可以被区分。",
      boundary: "本站中文均为工作释义；不以三部短经替代上座部注释、阿毘达磨或当代翻译争论，也不宣称它们与 T0099 已完成严格平行审定。",
      sources: "SN 56.11 · SN 38.14 · SN 36.6",
    },
    {
      label: "论释与现实照护",
      term: "三苦解释 · 医疗与创伤",
      supported: "后续传统对三苦、五取蕴与修道关系有更细分析；现实中的疾病、暴力、贫困和创伤也有真实外部条件。",
      boundary: "佛学概念页不能诊断疾病，不能代替医疗、心理、法律或危机支持；“第二支箭”尤其不得被用成受害者归责。",
      sources: "待受控论典、注疏与专业照护证据",
    },
  ],
  evidence: [
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099",
      title: "苦不是最终结论，而是四项任务的第一项",
      quote: "若比丘於苦聖諦當知、當解，於苦集聖諦當知、當斷，於苦滅聖諦當知、當證，於苦滅道跡聖諦當知、當修。",
      reading: "最小可证结论：苦要知解，但经文没有停在这里；同一句继续给出断集、证灭与修道。删掉后三项，才会把诊断误写成悲观主义。",
      locator: "T0099.015.0104b15–18",
      href: "/jingzang/zaahanjing/015-0104b#T0099.015.0104b15",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_015",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 56.11",
      title: "苦谛列出具体经验，也收束到五取蕴",
      quote: "Jātipi dukkhā, jarāpi dukkhā, byādhipi dukkho, maraṇampi dukkhaṁ … yampicchaṁ na labhati tampi dukkhaṁ—saṅkhittena pañcupādānakkhandhā dukkhā.",
      reading: "工作释义：生、老、病、死，与不爱者相会、与所爱者分离、所求不得皆苦；简要说，五取蕴是苦。省略号标示两项会合与分离，未把它们从取证范围中删除。",
      locator: "sn56.11:4.2",
      href: `${sn5611Path}#sn56.11:4.2`,
      sourceUrl: "https://suttacentral.net/sn56.11/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 38.14",
      title: "经文明确列出三种苦，并紧接一条道路",
      quote: "Tisso imā, āvuso, dukkhatā: dukkhadukkhatā, saṅkhāradukkhatā, vipariṇāmadukkhatā. … Ayameva kho, āvuso, ariyo aṭṭhaṅgiko maggo, etāsaṁ dukkhatānaṁ pariññāya.",
      reading: "工作释义：有三种 dukkhatā——苦苦、行苦、坏苦；为了遍知它们，有道路、有实践，即八支圣道。原文从分类直接转入道路，不把三苦留作消极世界观。",
      locator: "sn38.14:1.3–1.11",
      href: `${sn3814Path}#sn38.14:1.3`,
      sourceUrl: "https://suttacentral.net/sn38.14/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 36.6",
      title: "痛苦经验与追加反应，被比作第一箭和第二箭",
      quote: "So dve vedanā vedayati—kāyikañca, cetasikañca. … So ekaṁ vedanaṁ vedayati—kāyikaṁ, na cetasikaṁ.",
      reading: "工作释义：前一段说同时经历身体与心理两种感受，譬如连中两箭；后一段说只经历身体苦受，如中一箭而不再中第二箭。这是修习方向，不是对真实创伤的道德评判。",
      locator: "sn36.6:1.5–1.13 · 2.1–3.6",
      href: `${sn366Path}#sn36.6:1.5`,
      sourceUrl: "https://suttacentral.net/sn36.6/pli/ms",
      language: "pi",
    },
  ],
  translationNote: "巴利原文下方中文均为本站工作释义；“苦苦、行苦、坏苦”只作常见术语导航，不冒充受控古译，也不据此完成跨传统义理裁决。",
  misreadingsHeading: "先拆掉四种会把诊断变成伤害的读法。",
  misreadingsIntro: "承认苦，不等于否认快乐；学习反应，也不等于否认外部伤害。边界不清时，佛法语言很容易变成压迫人的话。",
  misconceptions: [
    {
      myth: "佛教说每一刻都只有痛苦",
      correction: "不成立。SN 36.6 同时承认乐受、苦受与不苦不乐受；dukkha 的范围比疼痛更广，但不能因此把所有经验改写成持续的难受。",
    },
    {
      myth: "三苦只是轻、中、重三个疼痛等级",
      correction: "过窄。SN 38.14 分列 dukkha、saṅkhāra、vipariṇāma 三种 dukkhatā，至少涉及直接苦、条件性与变易，不能只按疼痛强度排列。",
    },
    {
      myth: "第二支箭说明心理痛苦都是自己选的",
      correction: "危险。经文给出可修习的反应差异，不是在否定创伤、疾病与暴力的真实影响，更没有授权旁观者责怪受苦者。",
    },
    {
      myth: "修行就是忍着，不需要现实帮助",
      correction: "证据不支持。当前原典页不能替代医疗、心理、法律或危机支持；在伤害仍持续时，先求助和离开危险也是减少苦的现实行动。",
    },
  ],
  readingHeading: "从“哪里苦”读到“哪里不必再加一箭”。",
  readingIntro: "这条路径先确定范围，再辨分类、观察反应，最后回到知苦与修道的完整任务。",
  readingPath: [
    {
      step: "先定范围",
      title: "SN 56.11：苦谛具体包括什么",
      text: "沿原段核对生老病死、会合、分离、求不得与五取蕴，避免把 dukkha 缩成一个现代情绪词。",
      href: `${sn5611Path}#sn56.11:4.2`,
    },
    {
      step: "再分层次",
      title: "SN 38.14：三种 dukkhatā",
      text: "核对三个巴利复合词及其后紧接的八支圣道，理解分类为何服务于遍知与实践。",
      href: `${sn3814Path}#sn38.14:1.3`,
    },
    {
      step: "观察反应",
      title: "SN 36.6：第一箭与第二箭",
      text: "分清身体苦受与追加的心理反应，同时守住不责怪受苦者、不否认外部条件的应用边界。",
      href: `${sn366Path}#sn36.6:1.5`,
    },
    {
      step: "回到任务",
      title: "《杂阿含经》：苦当知解，集当断，灭当证，道当修",
      text: "最后把苦放回四谛全句：看清它，但不把它当终点；继续追查条件、止息与道路。",
      href: "/jingzang/zaahanjing/015-0104b#T0099.015.0104b15",
    },
  ],
  footerNote: "本页只综合 foxue.ai 当前受控的 T0099、SN 56.11、SN 38.14 与 SN 36.6。它不宣称汉巴材料已经完成严格平行审定，不替代论典、注疏、师承，也不把佛学解释当作医疗、心理、法律或危机处置。",
  updatedAt: "2026-09-15",
  footerActionLabel: "带着具体处境继续问",
  footerActionHref: "/wenjing",
  related: ["sidi", "bazhengdao", "wuyun", "wuchang", "yuanqi", "guanxin"],
} as const satisfies ConceptHub;
