import type { ConceptHub } from "@/lib/concept-hubs";

export const eightfoldPathGlobalSelectionAliases = [
  "八正道",
  "八聖道",
  "八圣道",
  "八支圣道",
  "八支聖道",
  "圣八支道",
  "聖八支道",
  "ariyo aṭṭhaṅgiko maggo",
  "Ariyaṁ vo, bhikkhave, aṭṭhaṅgikaṁ maggaṁ desessāmi",
  "ariyaṁ aṭṭhaṅgikaṁ maggaṁ",
  "ariya atthangika magga",
  "ariyam atthangikam maggam",
  "noble eightfold path",
  "Noble Eightfold Path",
  "正見、正志、正語、正業、正命、正方便、正念、正定",
  "正见、正志、正语、正业、正命、正方便、正念、正定",
  "正见、正思惟、正语、正业、正命、正精进、正念、正定",
  "正見、正思惟、正語、正業、正命、正精進、正念、正定",
] as const;

export const eightfoldPathPaliLimbSelectionAliases = [
  "sammādiṭṭhi",
  "sammāsaṅkappo",
  "sammāvācā",
  "sammākammanto",
  "sammāājīvo",
  "sammāājīvena",
  "sammāvāyāmo",
  "sammāsati",
  "sammāsamādhi",
  "sammāsamādhī",
] as const;

const eightfoldPathPaliSourcePath = "/jingzang/samyutta-nikaya-sn45/008-sn45-8-0001-0044";

export const eightfoldPathPaliDefinitionSourceHrefs = [
  "sn45.8:3.2",
  "sn45.8:4.2",
  "sn45.8:5.2",
  "sn45.8:6.2",
  "sn45.8:7.2",
  "sn45.8:8.2",
  "sn45.8:8.3",
  "sn45.8:8.4",
  "sn45.8:8.5",
  "sn45.8:9.2",
  "sn45.8:9.3",
  "sn45.8:9.4",
  "sn45.8:9.5",
  "sn45.8:10.2",
  "sn45.8:10.3",
  "sn45.8:10.4",
  "sn45.8:10.5",
].map((segmentId) => `${eightfoldPathPaliSourcePath}#${segmentId}`);

export const eightfoldPathConceptHub = {
  entry: {
    slug: "bazhengdao",
    title: "八正道",
    href: "/gainian/bazhengdao",
    summary: "汉巴并读《杂阿含经》《中阿含经》与 SN 45.8：八正道不是八条互不相干的自助建议，而是同属一条趋向苦灭道路的八支。",
    aliases: [...eightfoldPathGlobalSelectionAliases],
    selectionAliases: [...eightfoldPathGlobalSelectionAliases],
    scopedSelectionAliases: [{
      sourceHrefPrefix: `${eightfoldPathPaliSourcePath}#`,
      aliases: [...eightfoldPathPaliLimbSelectionAliases],
    }],
    selectionSourceHrefs: eightfoldPathPaliDefinitionSourceHrefs,
    prompt: "八正道是八条要逐项完成的规则吗？",
  },
  metadataTitle: "八正道｜概念 Hub",
  description: "从《杂阿含经》《中阿含经》与巴利 SN 45.8 的稳定原典理解八正道、八支关系及正志／正思惟、正方便／正精进等译语边界。",
  about: ["八正道", "八圣道", "杂阿含经", "中阿含经", "相应部", "ariyo aṭṭhaṅgiko maggo"],
  termCode: "bazhengdao",
  heading: "八正道",
  sectionTitle: "八支道路",
  sectionDescription: "八支有不同训练对象，却共同指向苦灭；先看每一支处理什么，再核对不同原典怎样命名和展开。",
  hero: {
    eyebrow: "概念 HUB · 汉巴八支原典并读",
    highlight: "八正道",
    beforeBreak: "，不是八条",
    afterBreak: "彼此孤立的清单。",
    lead:
      "《杂阿含经》把八支放在一条从明、正见到正定与解脱的关系中，也说它能断爱欲；《中阿含经》与 SN 45.8 则逐支说明其训练范围。阅读八正道的起点，不是给八项分别打分，而是观察见解、意向、言语、行动、生计、用力、觉察与定如何同属一条训练道路。",
    primaryActionLabel: "查看汉巴原典",
    primaryActionHref: "#evidence",
    secondaryActionLabel: "继续问经",
    secondaryActionHref: "/wenjing",
    lensNotes: [
      { label: "道路目标", text: "趋向苦灭 · 断爱欲" },
      { label: "八支关系", text: "从正见到正定次第而起" },
      { label: "术语边界", text: "正志／正思惟 · 正方便／正精进" },
    ],
  },
  stats: [
    { label: "可定位证据", value: "5 处" },
    { label: "原典语言", value: "汉文 · 巴利文" },
    { label: "道路支分", value: "8 支" },
    { label: "严格平行认定", value: "0 项" },
  ],
  termsHeading: "八支各有焦点，但没有一支单独构成整条道路。",
  termsIntro: "下列现代常用名只作导航；原典显示“正志／正思惟”“正方便／正精进”等译语差异，站内链接始终保留底本文字。",
  terms: [
    {
      label: "01 · sammādiṭṭhi",
      heading: "正见",
      detail: "SN 45.8 以知苦、集、灭、道界定；《中阿含经》把它放在观察诸行、涅槃止息与法的选择明达中。它不是脱离其余七支的意见标签。",
    },
    {
      label: "02 · sammāsaṅkappa",
      heading: "正思惟 · 正志",
      detail: "SN 45.8 指向出离、无瞋与不害的意向；T0099、T0026 在八支名目中作“正志”。现代常用“正思惟”不应覆盖古译原词。",
    },
    {
      label: "03 · sammāvācā",
      heading: "正语",
      detail: "SN 45.8 与汉译相关段落都把训练落到远离妄语、离间语、粗恶语与绮语等具体言说，而非只要求语气听起来温和。",
    },
    {
      label: "04 · sammākammanta",
      heading: "正业",
      detail: "原典把身体行动纳入道路。《中阿含经》说远离身恶行，SN 45.8 列出不杀生、不偷盗与不邪行的范围。",
    },
    {
      label: "05 · sammāājīva",
      heading: "正命",
      detail: "生计不是道路之外的私人区。《中阿含经》强调以法求生活所需、不以非法；SN 45.8 说舍离邪命而生活。",
    },
    {
      label: "06 · sammāvāyāma",
      heading: "正精进 · 正方便",
      detail: "T0099、T0026 作“正方便”，并用精进、勤求、不退等词展开；SN 45.8 分为令未生不善不生、已生不善断、未生善生、已生善增长。",
    },
    {
      label: "07 · sammāsati",
      heading: "正念",
      detail: "SN 45.8 展开为观身、受、心、法；《中阿含经》强调随念、复忆与不忘。它是八支之一，不等于把整条道路缩成注意当下。",
    },
    {
      label: "08 · sammāsamādhi",
      heading: "正定",
      detail: "《杂阿含经》说住心不乱、摄持寂止，SN 45.8 以四禅展开。这里只陈述经文范围，不把简短网页说明当成禅修指导。",
    },
  ],
  boundariesHeading: "可以对读八支结构，不能抹掉文本与译语差异。",
  boundariesIntro: "以下把三组已登记原典分开陈述；共同名目便于导航，但不自动证明段落互为严格平行经或定义完全相同。",
  traditions: [
    {
      label: "汉译《杂阿含经》",
      term: "八正道 · 八圣道",
      supported: "可直接支持八支名目、从明与正见展开的关系、断爱欲的道路目标，以及一组逐支简释。",
      boundary: "不同经次对八支的展开并不相同；本页不把第 749、752、784 经拼成一篇原经，也不替代平行经人工审定。",
      sources: "T0099.028.0198b · 0199a · 029.0203a",
    },
    {
      label: "汉译《中阿含经》",
      term: "苦灭道圣谛",
      supported: "《分别圣谛经》把八支置于苦灭道圣谛中，并从正见到正定逐支说明，适合连续阅读其定义语境。",
      boundary: "这里保留“正志”“正方便”等古译，不用现代常见名相覆盖底本，也不以单经概括全部阿含传统。",
      sources: "T0026.007.0469a–c",
    },
    {
      label: "巴利《相应部》",
      term: "ariyo aṭṭhaṅgiko maggo",
      supported: "SN 45.8 可直接支持正见至正定的逐支界定，包括四正勤、四念处与四禅的展开。",
      boundary: "中文只作本站工作释义；本页不宣称它与上述汉译段落已被双人复核为严格一一对应，也不代替注释传统。",
      sources: "SN 45.8",
    },
  ],
  evidence: [
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099 · 第 752 经",
      title: "八支是一条能断爱欲的道路",
      quote: "有八正道，能斷愛欲，謂正見、正志、正語、正業、正命、正方便、正念、正定。",
      reading: "最小可证结论：八支在此回答的是“有没有道路能断爱欲”，不是八条彼此无关的品格口号。",
      locator: "T0099.028.0199a10–11",
      href: "/jingzang/zaahanjing/028-0199a#T0099.028.0199a10",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_028",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099 · 第 749 经",
      title: "从明与正见展开，八支并非孤立",
      quote: "若起明為前相，生諸善法。……能生正見，正見生已，起正志、正語、正業、正命、正方便、正念、正定，次第而起。",
      reading: "这段把八支放在一条关系链中，并继续说正定之后得正解脱；当前证据不支持把它们拆成八项独立打卡。",
      locator: "T0099.028.0198b19–24",
      href: "/jingzang/zaahanjing/028-0198b#T0099.028.0198b19",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_028",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "《中阿含经》T0026 ·《分别圣谛经》",
      title: "在苦灭道圣谛中逐支说明",
      quote: "云何苦滅道聖諦？謂正見、正志、正語、正業、正命、正方便、正念、正定。……云何正方便？……若有精進方便，一向精勤求，有力趣向，專著不捨，亦不衰退，正伏其心。",
      reading: "这组连续段落从正见一直解释到正定；尤其显示古译“正方便”本身已用“精进方便”展开，不能只凭现代名相误判成不同支分。",
      locator: "T0026.007.0469a13–0469b29",
      href: "/jingzang/zhongahanjing/007-0469a#T0026.007.0469a13",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0026_007",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 45.8",
      title: "正见、意向、言语、行动与生计都有具体范围",
      quote: "dukkhe ñāṇaṁ … dukkhanirodhagāminiyā paṭipadāya ñāṇaṁ … nekkhammasaṅkappo, abyāpādasaṅkappo, avihiṁsāsaṅkappo … musāvādā veramaṇī … micchāājīvaṁ pahāya sammāājīvena jīvitaṁ kappeti",
      reading: "工作释义：正见关乎知苦集灭道；正意向指向出离、无瞋、不害；正语、正业与正命则进入可观察的言行和生活方式。",
      locator: "sn45.8:3.1–7.3",
      href: "/jingzang/samyutta-nikaya-sn45/008-sn45-8-0001-0044#sn45.8:3.1",
      sourceUrl: "https://suttacentral.net/sn45.8/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 45.8",
      title: "用力、觉察与定也在原文中被展开",
      quote: "anuppannānaṁ pāpakānaṁ akusalānaṁ dhammānaṁ anuppādāya … kāye kāyānupassī viharati … paṭhamaṁ jhānaṁ upasampajja viharati",
      reading: "工作释义：正精进从未生／已生的不善与善法展开；正念观察身、受、心、法；正定在本经以四禅说明。网页摘要不能替代完整原段与具资格的修习指导。",
      locator: "sn45.8:8.1–10.6",
      href: "/jingzang/samyutta-nikaya-sn45/008-sn45-8-0001-0044#sn45.8:8.1",
      sourceUrl: "https://suttacentral.net/sn45.8/pli/ms",
      language: "pi",
    },
  ],
  translationNote: "巴利原文下方中文均为本站工作释义。汉巴材料只作相关结构并读；当前没有双人审校结论支持严格平行经认定。",
  misreadingsHeading: "先拿掉四个会把道路拆散的快结论。",
  misreadingsIntro: "这些护栏不是新增教义，而是防止现代熟词遮住原典的目标、关系与译语层次。",
  misconceptions: [
    {
      myth: "八正道 = 八项独立打卡",
      correction: "证据不支持。《杂阿含经》把明、正见、其余诸支、正定与解脱放在连续关系中，并未把完成一支写成可以永久勾掉的一格。",
    },
    {
      myth: "“正”只是站对观点、评判别人",
      correction: "不完整。原典同时把“正”落实到意向、说话、身体行为、生计、努力、觉察与定；只用正见给他人贴标签，反而删掉了道路的大部分。",
    },
    {
      myth: "正念就是完整的八正道",
      correction: "不成立。正念是八支之一，SN 45.8 也明确另列正见、正意向、正语、正业、正命、正精进与正定。突出一支不能抹去其余七支。",
    },
    {
      myth: "正志和正思惟、正方便和正精进一定是不同项目",
      correction: "不能只看现代字面下结论。T0099、T0026 的八支名目作“正志”“正方便”，巴利相应词为 sammāsaṅkappa、sammāvāyāma；比较时应保留版本与语境。",
    },
  ],
  readingHeading: "先找道路目标，再读八支关系，最后逐支核对。",
  readingIntro: "这条路径先用最短汉译段落确定“为什么修”，再进入两组汉译定义与巴利原文；入门者不迷路，研究者也能核对坐标。",
  readingPath: [
    {
      step: "先看目标",
      title: "《杂阿含经》第 752 经：有八正道，能断爱欲",
      text: "先确认八支回答的问题与完整名目，避免把道路读成脱离苦灭目标的生活技巧。",
      href: "/jingzang/zaahanjing/028-0199a#T0099.028.0199a10",
    },
    {
      step: "再看关系",
      title: "《杂阿含经》第 749 经：从明与正见次第而起",
      text: "观察八支如何被置于前后相依的道路中，不把它们拆成八座孤岛。",
      href: "/jingzang/zaahanjing/028-0198b#T0099.028.0198b19",
    },
    {
      step: "核对汉译",
      title: "《中阿含经·分别圣谛经》逐支说明",
      text: "从正见连续读到正定，特别留意“正志”“正方便”等底本译语。",
      href: "/jingzang/zhongahanjing/007-0469a#T0026.007.0469a13",
    },
    {
      step: "核对巴利",
      title: "SN 45.8 的八支界定",
      text: "逐段打开巴利原文，核对四正勤、四念处与四禅怎样进入八支定义。",
      href: "/jingzang/samyutta-nikaya-sn45/008-sn45-8-0001-0044#sn45.8:3.1",
    },
    {
      step: "回到道谛",
      title: "四圣谛：为什么“道”必须修",
      text: "把八正道重新放回知苦、断集、证灭、修道的四项任务，避免只剩名相。",
      href: "/gainian/sidi",
    },
  ],
  footerNote: "本页只综合 foxue.ai 当前受控的 T0099、T0026 与 SN 45.8。它不把三组材料判作已审定的严格平行经，不替后世论典与宗派作完整教判，也不能替代具资格的师承、禅修指导或医疗与心理危机支持。",
  updatedAt: "2026-09-15",
  footerActionLabel: "带着八支继续问",
  footerActionHref: "/wenjing",
  related: ["sidi", "yuanqi", "guanxin", "wuzhu"],
} as const satisfies ConceptHub;
