import type { ConceptHub } from "@/lib/concept-hubs";

export const dependentOriginationConceptHub = {
  entry: {
    slug: "yuanqi",
    title: "缘起",
    href: "/gainian/yuanqi",
    summary: "汉巴并读《杂阿含经》与《相应部》：缘起说明可观察的条件关系，也同时保留止息与改变的可能。",
    aliases: [
      "缘起",
      "緣起",
      "因缘法",
      "因緣法",
      "十二因缘",
      "十二因緣",
      "十二缘起",
      "十二緣起",
      "paṭiccasamuppāda",
      "paticcasamuppada",
      "idappaccayatā",
      "idappaccayata",
    ],
    selectionAliases: [
      "此有故彼有",
      "此生故彼生",
      "此無故彼無",
      "此无故彼无",
      "此滅故彼滅",
      "此灭故彼灭",
      "法住法界",
      "paṭiccasamuppāda",
      "idappaccayatā",
    ],
    prompt: "缘起是不是说一切都注定了？",
  },
  metadataTitle: "缘起｜概念 Hub",
  description: "从《杂阿含经》与巴利《相应部》的稳定原典理解缘起、因缘法与此缘性，保留汉巴表达差异并辨清宿命论等误读。",
  about: ["缘起", "因缘法", "杂阿含经", "相应部", "paṭiccasamuppāda", "idappaccayatā"],
  termCode: "yuanqi",
  heading: "缘起",
  sectionTitle: "概念",
  sectionDescription: "缘起不是一句“万物互联”的感想，而是一种能回到生起、止息与具体条件逐项核对的观察框架。",
  hero: {
    eyebrow: "概念 HUB · 汉巴证据并读",
    highlight: "缘起",
    beforeBreak: "，不是宿命，",
    afterBreak: "而是看见什么条件正在起作用。",
    lead:
      "《杂阿含经》用“此有故彼有，此生故彼生”说明生起，也紧接“此无故彼无，此灭故彼灭”说明止息；巴利《相应部》则以 idappaccayatā 与 paṭiccasamuppāda 标示这种条件关系。条件可以被观察，止息才有可能被讨论。",
    primaryActionLabel: "查看汉巴证据",
    primaryActionHref: "#evidence",
    secondaryActionLabel: "继续问经",
    secondaryActionHref: "/wenjing",
    lensNotes: [
      { label: "汉译阿含", text: "此有故彼有，此灭故彼灭" },
      { label: "巴利相应部", text: "idappaccayatā · paṭiccasamuppāda" },
      { label: "共同底线", text: "条件性不等于宿命论" },
    ],
  },
  stats: [
    { label: "可定位证据", value: "4 处" },
    { label: "原典语言", value: "汉文 · 巴利文" },
    { label: "硬判平行经", value: "0 处" },
    { label: "证据状态", value: "受控原文" },
  ],
  termsHeading: "先分清“缘起”、缘生法与此缘性。",
  termsIntro: "相近词能互相照亮，但不能不经论证就当作完全同义；这里先保留各自出现的文本位置。",
  terms: [
    {
      label: "汉译阿含",
      heading: "因缘法",
      detail: "《杂阿含经》以“此有故彼有”说明因缘法，并把无明缘行等次第列为具体例子。",
    },
    {
      label: "汉译阿含",
      heading: "缘生法",
      detail: "同一段把由条件而生、会衰灭的诸支称作缘生法；这一区分值得保留，不能全部压成“缘起”一个词。",
    },
    {
      label: "巴利语",
      heading: "paṭiccasamuppāda",
      detail: "SN 12.20 用它标示缘起，并将 idappaccayatā 纳入说明；本站只作术语导航与工作释义。",
    },
    {
      label: "巴利语",
      heading: "idappaccayatā",
      detail: "可工作性地理解为“此缘性／特定条件性”：不是泛说万物神秘相连，而是追问此事依哪些条件发生。",
    },
  ],
  boundariesHeading: "相近表达可以并读，但不冒充已经完成的平行经裁决。",
  boundariesIntro: "本页并列四处可复核原文，只陈述它们各自能支持的最小结论。",
  traditions: [
    {
      label: "汉译《杂阿含经》",
      term: "此有故彼有 · 因缘法 · 缘生法",
      supported: "可直接支持条件生起与条件止息两面，也可支持因缘法与缘生法的文本区分。",
      boundary: "现有页面没有据此判定某段与某一巴利经为严格一一对应，也不统一全部汉译术语。",
      sources: "T0099.010.0066c–0067a · T0099.012.0084b",
    },
    {
      label: "巴利《相应部》",
      term: "idappaccayatā · paṭiccasamuppāda",
      supported: "可直接支持缘起的法则性表达、条件所生法趋向衰灭，以及避开“一切有／一切无”两端。",
      boundary: "中文仅为本站工作释义；不冒充古译、授权现代译本或全部上座部注释传统的定论。",
      sources: "SN 12.20 · SN 12.15",
    },
    {
      label: "后续论释与宗派",
      term: "十二支 · 三世两重因果 · 性空等",
      supported: "后世传统由缘起发展出不同的教学次第、论证与修习框架，适合另建受控证据页。",
      boundary: "当前证据只到经藏层，不用四段经文替阿毘达磨、中观、唯识或各宗注疏作完整总结。",
      sources: "待受控论典与注疏证据",
    },
  ],
  evidence: [
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099",
      title: "生起与止息必须放在一起读",
      quote: "此有故彼有，此生故彼生，謂緣無明有行，乃至純大苦聚集。……此無故彼無，此滅故彼滅。",
      reading: "最小可证结论：这段不只说明条件如何令苦聚生起，也说明相关条件止息时，苦聚如何止息；因此不能把缘起读成单向决定论。",
      locator: "T0099.010.0067a05–08",
      href: "/jingzang/zaahanjing/010-0067a#T0099.010.0067a05",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_010",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099",
      title: "因缘法与缘生法在经文中被明确分开",
      quote: "云何為因緣法？謂此有故彼有，謂緣無明行，緣行識，乃至如是如是純大苦聚集。云何緣生法？謂無明、行。若佛出世，若未出世，此法常住，法住法界。",
      reading: "经文先定义因缘法，再另问缘生法；“佛出世、若未出世”紧接无明、行等缘生法而说。保留这个语法位置，才能避免把两层术语混写。",
      locator: "T0099.012.0084b14–24",
      href: "/jingzang/zaahanjing/012-0084b#T0099.012.0084b14",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_012",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 12.20",
      title: "此缘性与缘起的法则性表达",
      quote: "Uppādā vā tathāgatānaṁ anuppādā vā tathāgatānaṁ, ṭhitāva sā dhātu dhammaṭṭhitatā dhammaniyāmatā idappaccayatā. … Ayaṁ vuccati, bhikkhave, paṭiccasamuppādo.",
      reading: "工作释义：无论如来出现与否，这种条件关系及其法则性都成立；这种如是、不异与此缘性，被称为缘起。",
      locator: "sn12.20:2.3 · 3.16–17",
      href: "/jingzang/samyutta-nikaya-sn12/020-sn12-20-0001-0064#sn12.20:2.3",
      sourceUrl: "https://suttacentral.net/sn12.20/pli/ms",
      language: "pi",
    },
    {
      kind: "相关证据",
      canon: "巴利《相应部》SN 12.15",
      title: "缘起避开“一切有”与“一切无”两端",
      quote: "‘Sabbamatthī’ti kho, kaccāna, ayameko anto. ‘Sabbaṁ natthī’ti ayaṁ dutiyo anto. Ete te, kaccāna, ubho ante anupagamma majjhena tathāgato dhammaṁ deseti.",
      reading: "工作释义：“一切有”是一端，“一切无”是另一端；不走这两端，如来以中道说明无明缘行等生起与止息。这里与汉译阿含相关表达并读，但不硬判为同一文本见证。",
      locator: "sn12.15:3.1–9",
      href: "/jingzang/samyutta-nikaya-sn12/015-sn12-15-0001-0024#sn12.15:3.1",
      sourceUrl: "https://suttacentral.net/sn12.15/pli/ms",
      language: "pi",
    },
  ],
  translationNote: "巴利原文下方中文均为本站工作释义，只说明本页的取证范围；汉巴相关表达可并读，但本页不据此宣称已经完成严格平行经认定。",
  misreadingsHeading: "先去掉四个会遮住条件的快结论。",
  misreadingsIntro: "这些护栏不替任何宗派下最终定义，只防止现代口号越过现有原典能支持的范围。",
  misconceptions: [
    {
      myth: "缘起 = 一切都神秘相连",
      correction: "过宽。现有证据列出可追问的具体条件，并分别说明生起与止息；不是看到两件事同时发生，就可以宣布它们有神秘因缘。",
    },
    {
      myth: "缘起 = 宿命论",
      correction: "不成立。若只看到“此有故彼有”而删掉“此无故彼无、此灭故彼灭”，就删除了同一段经文给出的改变方向。",
    },
    {
      myth: "缘起只解释事物怎样生起",
      correction: "不完整。《杂阿含经》与 SN 12.15 都把生起和止息并列；理解条件，也包括辨认什么止息时，苦的链条不再继续。",
    },
    {
      myth: "缘起是佛陀创造的宇宙法则",
      correction: "现有汉巴证据都强调：如来出现与否，这种条件秩序并不因此被创造；佛陀所做的是觉知、说明并揭示它。",
    },
  ],
  readingHeading: "先看一条可改变的条件链，再比较汉巴表达。",
  readingIntro: "这条路径从最直观的生灭公式开始，再逐步分清中道语境、术语层次与条件所生法。",
  readingPath: [
    {
      step: "先读生灭",
      title: "《杂阿含经》“此有故彼有……此灭故彼灭”",
      text: "把生起与止息放在同一视野里，先排除“缘起等于命中注定”的误读。",
      href: "/jingzang/zaahanjing/010-0067a#T0099.010.0067a05",
    },
    {
      step: "汉巴并读",
      title: "SN 12.15 避开“一切有／一切无”两端",
      text: "比较相近的中道表达，同时保留经号、语言与段落边界，不先宣布严格一一对应。",
      href: "/jingzang/samyutta-nikaya-sn12/015-sn12-15-0001-0024#sn12.15:3.1",
    },
    {
      step: "再分术语",
      title: "《杂阿含经》因缘法与缘生法",
      text: "看同一经文如何区分条件法则与由条件而生、趋向老灭的诸支。",
      href: "/jingzang/zaahanjing/012-0084b#T0099.012.0084b14",
    },
    {
      step: "最后核法则性",
      title: "SN 12.20 此缘性与条件所生法",
      text: "从 idappaccayatā 读到条件所生法的无常、衰灭与止息，检查自己是否又把缘起固化成实体。",
      href: "/jingzang/samyutta-nikaya-sn12/020-sn12-20-0001-0064#sn12.20:2.3",
    },
  ],
  footerNote: "本页只综合 foxue.ai 当前受控的《杂阿含经》与巴利《相应部》样本。它不替学界裁决严格平行经关系，也不把后世阿毘达磨、中观、唯识与各宗注疏压成一个答案。",
  updatedAt: "2026-09-15",
  footerActionLabel: "带着条件继续问",
  footerActionHref: "/wenjing",
  related: ["wuchang", "wuwo", "kong", "guanxin"],
} as const satisfies ConceptHub;
