import type { ConceptHub } from "@/lib/concept-hubs";

export const expandedConceptHubs = [
  {
    entry: {
      slug: "wuchang",
      title: "无常",
      href: "/gainian/wuchang",
      summary: "从《佛说无常经》与《佛说五蕴皆空经》现有证据理解“无常”不是悲观口号，而是如实看见生灭与衰变。",
      aliases: ["无常", "無常", "老病死", "生者皆归死", "生者皆歸死", "无常吞", "一切有为法", "變衰", "变衰"],
      prompt: "无常是不是悲观？",
    },
    metadataTitle: "无常｜概念 Hub",
    description: "从《佛说无常经》与《佛说五蕴皆空经》等现有证据理解“无常”的观察范围、修行指向与常见误解。",
    about: ["无常", "佛说无常经", "五蕴皆空", "老病死"],
    termCode: "wuchang",
    heading: "无常",
    sectionTitle: "概念",
    sectionDescription: "这里先把“无常”从励志口号或丧气判断里拆出来，回到可定位的经文场景。",
    hero: {
      eyebrow: "概念 HUB · 受控证据版",
      highlight: "无常",
      beforeBreak: "，不是一句",
      afterBreak: "劝你消极的口号。",
      lead:
        "现有证据反复指出：生者归死、容颜衰变、老病死不称意，连色受想行识也都不稳固。无常不是为了制造绝望，而是为了让执取松动，转向较少苦的路。",
      primaryActionLabel: "查看原典证据",
      primaryActionHref: "#evidence",
      secondaryActionLabel: "继续问经",
      secondaryActionHref: "/wenjing",
      lensNotes: [
        { label: "可直接支持", text: "老病死与诸行败坏" },
        { label: "五蕴观察", text: "色受想行识皆不常住" },
        { label: "共同底线", text: "不是悲观宿命" },
      ],
    },
    stats: [
      { label: "可定位证据", value: "4 处" },
      { label: "直接文本", value: "2 部" },
      { label: "统一宗派裁决", value: "0 个" },
      { label: "证据状态", value: "受控原文" },
    ],
    termsHeading: "先问：无常说的是“坏掉”，还是“如实变化”？",
    termsIntro: "现有证据里，“无常”既指衰败、老病死，也指一切条件法无法固定停住。它不是一句抽象世界观，而是观察与修行入口。",
    terms: [
      {
        label: "汉译佛典",
        heading: "无常",
        detail: "《佛说无常经》把它直接落在生死、病苦、衰变和轮转之上，不让人把“无常”只当成哲学名词。",
      },
      {
        label: "五蕴观察",
        heading: "色为是常？为是无常？",
        detail: "《佛说五蘊皆空经》把无常放进五蕴观察：既不常住，也不听命于“我要它永不变”的愿望。",
      },
      {
        label: "现代转译",
        heading: "变化 · 生灭 · 坏散",
        detail: "这些词可以帮助定位感受，但不能替代经文语境；“变化”若脱离苦、执取与出离，就会失掉佛典方向。",
      },
      {
        label: "修行边界",
        heading: "无常 ≠ 宿命",
        detail: "现有证据把无常与“当行不死门”“能灭诸烦惱”并列，说明它的功能是催促清醒与出离，不是劝人躺平。",
      },
    ],
    boundariesHeading: "同一个“无常”，也要分清观察对象与修行指向。",
    boundariesIntro: "下列边界只说明当前证据能支持到哪里，不把不同传统、论释与仪轨混成一个总答案。",
    traditions: [
      {
        label: "《佛说无常经》语境",
        term: "生灭 · 老病死 · 不死门",
        supported: "可直接支持“未曾有一事，不被无常吞”，以及从老病死的不可爱转向真实法与不死门的修行指向。",
        boundary: "本页不把《佛说无常经》后段的临终劝导与殡葬实践自动推广成所有佛教共同仪轨。",
        sources: "T0801",
      },
      {
        label: "五蕴观察语境",
        term: "色受想行识无常",
        supported: "可直接支持五蕴不常住，因此不应执为可支配的“我”或“我所有”。",
        boundary: "这里不展开后世阿毘达磨与论书对刹那、法体的细密分析，也不把经文简化成心理学隐喻。",
        sources: "T0102",
      },
      {
        label: "后续论释与宗派",
        term: "阿含 · 般若 · 禅修等",
        supported: "这些传统都可能从无常出发，但论证层次、措辞和修行次第并不相同，值得分别做证据页。",
        boundary: "当前页面不裁决哪一种才是“唯一正确的无常观”，也不把所有后世说法打包成同义句。",
        sources: "待受控论典与注疏证据",
      },
    ],
    evidence: [
      {
        kind: "直接证据",
        canon: "《佛说无常经》T0801",
        title: "没有一件条件事物能逃过坏灭",
        quote: "生者皆歸死，容顏盡變衰；強力病所侵，無能免斯者。……未曾有一事，不被無常吞。",
        reading: "最小可证结论：无常首先不是抽象词，而是直指衰变、病苦、死亡与一切条件法的败坏。",
        locator: "T0801.001.0745b24",
        href: "/jingzang/taisho-t0801/001-0745b#T0801.001.0745b24",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0801_001",
        language: "zh-Hans",
      },
      {
        kind: "直接证据",
        canon: "《佛说无常经》T0801",
        title: "看见无常，是为了改走离苦之路",
        quote: "是故勸諸人，諦聽真實法，共捨無常處，當行不死門。佛法如甘露，除熱得清涼，一心應善聽，能滅諸煩惱。",
        reading: "经文把无常和“真實法”“不死門”“滅煩惱”连在一起，因此它不是让人沉下去，而是逼人重新选择方向。",
        locator: "T0801.001.0745c11",
        href: "/jingzang/taisho-t0801/001-0745c#T0801.001.0745c11",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0801_001",
        language: "zh-Hans",
      },
      {
        kind: "直接证据",
        canon: "《佛说五蘊皆空经》T0102",
        title: "五蕴观察从“无常”而不是从口号开始",
        quote: "復次苾芻！於汝意云何？色為是常？為是無常？」白言：「大德！色是無常。」",
        reading: "这里把“无常”放进色受想行识的观察次第，说明它既是事实判断，也服务于松动执取。",
        locator: "T0102.001.0499c14",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c14",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0102_001",
        language: "zh-Hans",
      },
      {
        kind: "相关证据",
        canon: "《金刚般若波罗蜜经》T0235",
        title: "一切有为法的短暂无定",
        quote: "一切有爲法，如夢幻泡影，如露亦如電，應作如是觀。",
        reading: "这段相关证据强调条件法不应被执为固定实体；它能帮助理解无常为何不是悲观，而是校正抓取方式。",
        locator: "T0235.001.0752c17",
        href: "/jingzang/jingangjing/001-0752c#T0235.001.0752c17",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0235_001",
        language: "zh-Hans",
      },
    ],
    misreadingsHeading: "先停下四种会把“无常”读歪的快结论。",
    misreadingsIntro: "这些护栏只做一件事：防止“看见变化”被误读成“否定意义”或“拒绝行动”。",
    misconceptions: [
      {
        myth: "无常 = 悲观或倒霉预言",
        correction: "不成立。当前证据把无常与“真實法”“不死門”“滅煩惱”并列，它的作用是让人清醒，不是把人压垮。",
      },
      {
        myth: "既然都会坏，就不用行善修行",
        correction: "与经文相反。《佛说无常经》正因为指出败坏与死苦，才劝人转向佛法、离苦与善行。",
      },
      {
        myth: "无常只是在说死亡，不关当下",
        correction: "过窄。五蕴的感受、想法、意志与识别活动同样不常住，因此无常也发生在你此刻的经验里。",
      },
      {
        myth: "看见无常就该对关系和责任冷掉",
        correction: "证据不支持。无常要松动的是执取，不是让你撤销伦理、照料与现实判断。",
      },
    ],
    readingHeading: "先看败坏事实，再看它如何松开执取。",
    readingIntro: "这条路径故意从最直观的证据开始：先看生灭与衰变，再回到五蕴与行为方式。",
    readingPath: [
      {
        step: "先看事实",
        title: "《佛说无常经》“未曾有一事，不被无常吞”",
        text: "先正面看见一切条件法都会变坏，不再拿“以后再说”遮住事实。",
        href: "/jingzang/taisho-t0801/001-0745b#T0801.001.0745b24",
      },
      {
        step: "再看方向",
        title: "《佛说无常经》“當行不死門”",
        text: "再看经文如何把无常从灾难描述转成修行入口，而不是停在情绪反应里。",
        href: "/jingzang/taisho-t0801/001-0745c#T0801.001.0745c11",
      },
      {
        step: "带回五蕴",
        title: "《佛说五蘊皆空经》“色是無常”",
        text: "最后把无常带回身体、感受、意志与识别活动，理解它为何能松动“我应该永远这样”的抓取。",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c14",
      },
    ],
    footerNote: "本页只综合 foxue.ai 当前受控的《佛说无常经》《佛说五蘊皆空经》与相关《金刚经》样本。它不替所有传统裁决无常的完整义理，也不把临终、仪轨或后世论释混成一个答案。",
    updatedAt: "2026-08-20",
    footerActionLabel: "带着问题继续问",
    footerActionHref: "/wenjing",
    related: ["wuwo", "wuzhu", "kong"],
  },
  {
    entry: {
      slug: "wuwo",
      title: "无我",
      href: "/gainian/wuwo",
      summary: "从《佛说五蘊皆空经》与《外道问圣大乘法无我义经》现有证据理解“无我”不是否认经验，而是不把身心执为主宰。",
      aliases: ["无我", "無我", "我所", "无我义", "無我義", "身无我", "身無我", "補特伽羅", "补特伽罗", "五蘊無我", "五蕴无我"],
      prompt: "无我是不是否定‘我’的存在？",
    },
    metadataTitle: "无我｜概念 Hub",
    description: "从《佛说五蘊皆空经》与《外道问圣大乘法无我义经》等现有证据理解“无我”的观察范围、传统边界与常见误解。",
    about: ["无我", "五蘊皆空", "无我义", "佛教概念"],
    termCode: "wuwo",
    heading: "无我",
    sectionTitle: "概念",
    sectionDescription: "这一页先处理最常见的误会：无我不是删掉经验，而是不再把身心与身份执成固定主宰。",
    hero: {
      eyebrow: "概念 HUB · 受控证据版",
      highlight: "无我",
      beforeBreak: "，不是把经验",
      afterBreak: "整段删掉。",
      lead:
        "现有证据把“无我”首先落在五蕴与身心观察上：色受想行识不应被当成固定主宰，也不应被认作“我所有”。它要拆的是执取方式，不是抹掉责任、关系和感受。",
      primaryActionLabel: "查看原典证据",
      primaryActionHref: "#evidence",
      secondaryActionLabel: "继续问经",
      secondaryActionHref: "/wenjing",
      lensNotes: [
        { label: "五蕴观察", text: "色受想行识非我" },
        { label: "身心拆解", text: "周遍内外不见本性" },
        { label: "共同底线", text: "不是否认经验" },
      ],
    },
    stats: [
      { label: "可定位证据", value: "4 处" },
      { label: "直接文本", value: "3 处" },
      { label: "统一宗派裁决", value: "0 个" },
      { label: "证据状态", value: "受控原文" },
    ],
    termsHeading: "先问：无我拆掉的，到底是什么？",
    termsIntro: "当前证据里，“无我”拆掉的是把身心、角色、关系或诸法立成固定主宰的动作，而不是否认经验事实本身。",
    terms: [
      {
        label: "汉译阿含语境",
        heading: "色不是我",
        detail: "《佛说五蘊皆空经》把无我落在五蕴观察：若能随意支配，它才像“我”；既不由你作主，就不应执为我。",
      },
      {
        label: "大乘问答语境",
        heading: "身与本性，體本空故",
        detail: "《外道问圣大乘法无我义经》从身体部件与“本性”两层追问，指出遍观内外都不见可抓住的固定主宰。",
      },
      {
        label: "术语导航",
        heading: "anattā / anātman",
        detail: "这里只作跨语言导航；当前直接证据主轴仍是汉译样本与一条相关巴利段落，不把不同传统自动合并成同一句话。",
      },
      {
        label: "实践边界",
        heading: "无我 ≠ 无责任",
        detail: "现有证据要松开的，是“我”“我所”的固执，不是把伦理、因果或对他人的照料一起取消。",
      },
    ],
    boundariesHeading: "同样说“无我”，也要分清文本对象与论证层次。",
    boundariesIntro: "以下边界只描述当前证据能支持到哪里，不替任何宗派作最终裁决。",
    traditions: [
      {
        label: "五蕴观察语境",
        term: "色受想行识非我",
        supported: "可直接支持“色不是我；受想行識，亦復如是”，以及“知無有我及以我所”的观察方向。",
        boundary: "这里不展开后世阿毘达磨关于人无我、法无我的细分，也不把五蕴观察压缩成现代心理口号。",
        sources: "T0102",
      },
      {
        label: "大乘问答语境",
        term: "無自無他 · 無補特伽羅",
        supported: "可直接支持从身体部件、内外观察与“無自無他、無補特伽羅”等句子来说明不可执取的边界。",
        boundary: "当前样本不足以代表所有大乘论典的完整无我论证，也不等于中观、唯识等后世体系已经被本页概括完毕。",
        sources: "T0846",
      },
      {
        label: "跨传统相关证据",
        term: "空于我与我所",
        supported: "相关巴利段落能帮助确认：至少在一个早期语境里，“空”与“無我／我所”并不隔绝。",
        boundary: "它只能提供边界支持，不能用一条相关段落就抹平不同语境对“无我”的全部差异。",
        sources: "SN 35.85（相关）",
      },
    ],
    evidence: [
      {
        kind: "直接证据",
        canon: "《佛说五蘊皆空经》T0102",
        title: "五蕴并不是可支配的“我”",
        quote: "汝等當知，色不是我，若是我者，色不應病及受苦惱。……是故當知，色不是我；受想行識，亦復如是。",
        reading: "这段把“是否由我作主”作为观察切口：既然色受想行识并不听命于“我欲如是”，就不应执为我。",
        locator: "T0102.001.0499c10",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c10",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0102_001",
        language: "zh-Hans",
      },
      {
        kind: "直接证据",
        canon: "《佛说五蘊皆空经》T0102",
        title: "无我也包括“无我所”",
        quote: "凡所有色，若過去未來現在，內外麁細，若勝若劣、若遠若近，悉皆無我。……觀此五取蘊，知無有我及以我所。",
        reading: "当前可直接支持的最小结论不是“什么都没有”，而是：无论哪一类色与五取蕴，都不应被执成“我”或“我所有”。",
        locator: "T0102.001.0499c18",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c18",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0102_001",
        language: "zh-Hans",
      },
      {
        kind: "直接证据",
        canon: "《外道问圣大乘法无我义经》T0846",
        title: "周遍身心内外，也不见固定本性",
        quote: "當觀全身，髮、甲、皮、毛、兩手、雙足，至於脂、筋、脾、腸、骨髓等事，周遍內外，不見本性。",
        reading: "这段把“无我”落实成拆解式观察：把身体部件逐一展开，仍看不见一个可固定指认为主宰的核心。",
        locator: "T0846.001.0934b01",
        href: "/jingzang/taisho-t0846/001-0934b#T0846.001.0934b01",
        sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0846_001",
        language: "zh-Hans",
      },
      {
        kind: "相关证据",
        canon: "巴利《相应部》SN 35.85",
        title: "空于“我”与“我所”",
        quote: "Yasmā ca kho, ānanda, suññaṁ attena vā attaniyena vā tasmā suñño lokoti vuccati.",
        reading: "工作释义：因为世间空于我或我所，所以说世间是空。它为“无我 / 我所”提供了跨传统的相关边界。",
        locator: "sn35.85:1.4",
        href: "/jingzang/samyutta-nikaya-sn35/068-sn35-85-0001-0013#sn35.85:1.4",
        sourceUrl: "https://suttacentral.net/sn35.85/pli/ms",
        language: "pi",
      },
    ],
    translationNote: "巴利文下方中文为本站工作释义，用来说明取证范围，不冒充受控古译或现代授权译本。",
    misreadingsHeading: "先停下四种最常把“无我”读偏的等号。",
    misreadingsIntro: "这些护栏不是新教义，只是防止把“无我”读成对现实、关系或伦理的粗暴否定。",
    misconceptions: [
      {
        myth: "无我 = 什么都不存在",
        correction: "不成立。当前证据是否定“可固定执取的主宰者”，不是否认身体、感受、关系与因果的存在。",
      },
      {
        myth: "无我 = 不能再说“我”“我的”",
        correction: "过度字面化。经文要处理的是执取与误认，不是要你在日常语言里彻底失去代词。",
      },
      {
        myth: "无我 = 不必承担责任",
        correction: "危险。把“无我”拿来替自己卸责，恰好说明“我所”还抓得很紧；当前证据完全不支持这种用法。",
      },
      {
        myth: "所有传统说的无我完全一样",
        correction: "过度合并。五蕴观察、大乘问答、后世论释与修行系统有不同层次，必须保留来源与边界。",
      },
    ],
    readingHeading: "先拆五蕴，再拆“主宰者”的想象。",
    readingIntro: "这条路径故意不从抽象哲学开始，而从经文已经给出的观察顺序往下走。",
    readingPath: [
      {
        step: "先看五蕴",
        title: "《佛说五蘊皆空经》“色不是我”",
        text: "先从身体、感受、想法、意志与识别活动切入，观察它们为什么不是能任意支配的“我”。",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c10",
      },
      {
        step: "再看我所",
        title: "《佛说五蘊皆空经》“知無有我及以我所”",
        text: "再把观察扩到“我所有”的抓取方式，理解为什么问题不只在“我”，也在占有心。",
        href: "/jingzang/taisho-t0102/001-0499c#T0102.001.0499c18",
      },
      {
        step: "扩大到身心拆解",
        title: "《外道问圣大乘法无我义经》“周遍內外，不見本性”",
        text: "最后看经文如何把无我推到身体部件与内外观察，让“主宰者”无法继续躲在抽象词里。",
        href: "/jingzang/taisho-t0846/001-0934b#T0846.001.0934b01",
      },
    ],
    footerNote: "本页只综合 foxue.ai 当前受控的《佛说五蘊皆空经》《外道问圣大乘法无我义经》与一条相关巴利样本。它不替所有宗派裁决“无我”的终极定义，也不把不同传统论证强行压成一句话。",
    updatedAt: "2026-08-20",
    footerActionLabel: "带着问题继续问",
    footerActionHref: "/wenjing",
    related: ["kong", "wuchang", "guanxin"],
  },
] as const satisfies readonly ConceptHub[];
