import type { ConceptHub } from "@/lib/concept-hubs";

export const fourNobleTruthsConceptHub = {
  entry: {
    slug: "sidi",
    title: "四圣谛",
    href: "/gainian/sidi",
    summary: "汉巴并读《杂阿含经》与《相应部》：四圣谛不是四句悲观结论，而是知苦、断集、证灭、修道的四项任务。",
    aliases: [
      "四圣谛",
      "四聖諦",
      "四谛",
      "四諦",
      "苦集灭道",
      "苦集滅道",
      "cattāri ariyasaccāni",
      "cattari ariyasaccani",
      "four noble truths",
    ],
    selectionAliases: [
      "苦聖諦",
      "苦圣谛",
      "苦集聖諦",
      "苦集圣谛",
      "苦滅聖諦",
      "苦灭圣谛",
      "苦滅道跡聖諦",
      "苦灭道迹圣谛",
      "三轉十二行",
      "三转十二行",
      "dukkhaṁ ariyasaccaṁ",
      "dukkhasamudayaṁ ariyasaccaṁ",
      "dukkhanirodhaṁ ariyasaccaṁ",
      "dukkhanirodhagāminī paṭipadā ariyasaccaṁ",
    ],
    prompt: "四圣谛是不是说人生只有痛苦？",
  },
  metadataTitle: "四圣谛｜概念 Hub",
  description: "从《杂阿含经》与巴利《相应部》的稳定原典理解四圣谛：知苦、断集、证灭、修道，并辨清悲观论等常见误读。",
  about: ["四圣谛", "苦集灭道", "杂阿含经", "相应部", "cattāri ariyasaccāni"],
  termCode: "sidi",
  heading: "四圣谛",
  sectionTitle: "四项任务",
  sectionDescription: "四圣谛不是背完四个名词，而是把苦、苦的条件、止息与道路分别落实为应完成的任务。",
  hero: {
    eyebrow: "概念 HUB · 汉巴任务结构并读",
    highlight: "四圣谛",
    beforeBreak: "，不是四句",
    afterBreak: "悲观结论。",
    lead:
      "《杂阿含经》没有让人停在“有苦”这句话上，而是明确要求：苦当知解，集当断，灭当证，道当修。巴利 SN 56.11 也逐项保留应遍知、应舍断、应证得、应修习的任务。四谛之所以完整，正在于灭与道没有被删掉。",
    primaryActionLabel: "查看汉巴证据",
    primaryActionHref: "#evidence",
    secondaryActionLabel: "继续问经",
    secondaryActionHref: "/wenjing",
    lensNotes: [
      { label: "如实诊断", text: "苦应知解" },
      { label: "改变条件", text: "集应断 · 灭应证" },
      { label: "落实道路", text: "道应修" },
    ],
  },
  stats: [
    { label: "可定位证据", value: "4 处" },
    { label: "原典语言", value: "汉文 · 巴利文" },
    { label: "实践任务", value: "4 项" },
    { label: "证据状态", value: "受控原文" },
  ],
  termsHeading: "每一谛都回答不同问题，也要求不同动作。",
  termsIntro: "“知、断、证、修”不能互换：看清处境，不等于已经改变条件；知道有道路，也不等于已经修习。",
  terms: [
    {
      label: "苦谛 · dukkha",
      heading: "知 · 遍知",
      detail: "如实辨认生、老、病、死、爱别离、求不得与五取蕴等苦的范围；这是诊断，不是宣称一切经验都毫无价值。",
    },
    {
      label: "集谛 · samudaya",
      heading: "断 · 舍断",
      detail: "追查令苦续起的条件。SN 56.11 在这一段指向伴随贪喜、到处寻求满足的渴爱；重点是可观察、可改变的续起机制。",
    },
    {
      label: "灭谛 · nirodha",
      heading: "证 · 证得",
      detail: "经文把渴爱的离贪、止息、放下与解脱列为可证的方向；灭谛使四谛不是绝望诊断，也不等于把一切抹成虚无。",
    },
    {
      label: "道谛 · magga",
      heading: "修 · 修习",
      detail: "SN 56.11 把趋向苦灭的道路具体落在八支圣道。道谛要求训练与实践，不是仅仅同意一个道理。",
    },
  ],
  boundariesHeading: "结构相近可以并读，文本身份仍须分别保留。",
  boundariesIntro: "以下只陈述《杂阿含经》与 SN 56.11 当前段落能直接支持的最小结论，不替学界裁决严格平行经关系。",
  traditions: [
    {
      label: "汉译《杂阿含经》",
      term: "苦 · 集 · 灭 · 道迹",
      supported: "可直接支持四圣谛的名目、知解／断／证／修四项任务，以及三转十二行的经文结构。",
      boundary: "本页不以一卷经文概括全部汉译阿含传统，也不消除“道迹”等译语与现代常用词之间的差别。",
      sources: "T0099.015.0103c–0104b",
    },
    {
      label: "巴利《相应部》",
      term: "cattāri ariyasaccāni",
      supported: "可直接支持四谛的界定、苦集灭道的内容，以及每一谛从认识、应办任务到已办的三层展开。",
      boundary: "中文只作本站工作释义；不冒充古译、授权现代译本或全部上座部注释传统的定论。",
      sources: "SN 56.11",
    },
    {
      label: "后续论释与宗派",
      term: "四谛十六行相等",
      supported: "后世传统对四谛发展出细密的认识论、修道次第与观行体系，适合另建带论典证据的专题。",
      boundary: "当前页面停在经藏证据层，不以四段经文替阿毘达磨、瑜伽行、中观、天台等传统作统一总结。",
      sources: "待受控论典与注疏证据",
    },
  ],
  evidence: [
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099",
      title: "四谛各有一项不能互换的任务",
      quote: "若比丘於苦聖諦當知、當解，於苦集聖諦當知、當斷，於苦滅聖諦當知、當證，於苦滅道跡聖諦當知、當修。",
      reading: "最小可证结论：四谛不是四个静态判断；苦要知解，集要断，灭要证，道要修。只讲“人生是苦”，删掉了同段经文的后三项任务。",
      locator: "T0099.015.0104b15–18",
      href: "/jingzang/zaahanjing/015-0104b#T0099.015.0104b15",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_015",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "《杂阿含经》T0099",
      title: "从当知当办到已完成的三转十二行",
      quote: "此苦聖諦，本所未曾聞法，當正思惟。……苦集聖諦已知當斷……苦滅聖諦已知當作證……苦滅道跡聖諦已知當修。",
      reading: "随后经文再逐项说“已知、已断、已作证、已修”，并总称“四圣谛三转十二行”。这使认识、任务与完成状态可以被区分。",
      locator: "T0099.015.0103c14–0104a08",
      href: "/jingzang/zaahanjing/015-0103c#T0099.015.0103c14",
      sourceUrl: "https://cbetaonline.dila.edu.tw/zh/T0099_015",
      language: "zh-Hant",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 56.11",
      title: "苦、集、灭、道分别被界定",
      quote: "Idaṁ kho pana, bhikkhave, dukkhaṁ ariyasaccaṁ … dukkhasamudayaṁ ariyasaccaṁ … dukkhanirodhaṁ ariyasaccaṁ … dukkhanirodhagāminī paṭipadā ariyasaccaṁ.",
      reading: "工作释义：这是苦圣谛、苦集圣谛、苦灭圣谛，以及导向苦灭之道圣谛。原段继续说明苦的范围、渴爱、止息与八支圣道。",
      locator: "sn56.11:4.1–10",
      href: "/jingzang/samyutta-nikaya-sn56/011-sn56-11-0001-0060#sn56.11:4.1",
      sourceUrl: "https://suttacentral.net/sn56.11/pli/ms",
      language: "pi",
    },
    {
      kind: "直接证据",
      canon: "巴利《相应部》SN 56.11",
      title: "四项任务在巴利原文中逐一展开",
      quote: "Dukkhaṁ ariyasaccaṁ pariññeyyaṁ … dukkhasamudayaṁ ariyasaccaṁ pahātabbaṁ … dukkhanirodhaṁ ariyasaccaṁ sacchikātabbaṁ … dukkhanirodhagāminī paṭipadā ariyasaccaṁ bhāvetabbaṁ.",
      reading: "工作释义：苦应遍知，苦集应舍断，苦灭应证得，趋向苦灭之道应修习。这里与汉译任务结构相关并读，但本页不据此硬判文本关系。",
      locator: "sn56.11:5.2 · 6.2 · 7.2 · 8.2",
      href: "/jingzang/samyutta-nikaya-sn56/011-sn56-11-0001-0060#sn56.11:5.2",
      sourceUrl: "https://suttacentral.net/sn56.11/pli/ms",
      language: "pi",
    },
  ],
  translationNote: "巴利原文下方中文均为本站工作释义。汉巴两组材料在四谛与任务结构上可作相关并读，但本页没有据此宣称已经完成严格平行经认定。",
  misreadingsHeading: "先拿掉四个会把道路截断的快结论。",
  misreadingsIntro: "误读通常来自只保留四谛的一部分：只讲苦、只背名词，或把止息与修道解释成消极退场。",
  misconceptions: [
    {
      myth: "四圣谛 = 人生只有痛苦",
      correction: "不完整。经文不是把所有经验压成一句“都很苦”，而是辨认特定苦及五取蕴，并把集、灭、道与知断证修同时列出。删除灭与道，才会把四谛改写成悲观论。",
    },
    {
      myth: "记住苦集灭道，就已经懂了四谛",
      correction: "经文区分认识、应完成的任务与任务已完成。能复述四个名词，只处在入口；知苦、断集、证灭、修道不能由背诵自动替代。",
    },
    {
      myth: "集谛是在责怪受苦的人",
      correction: "当前原文把注意力放在令苦续起的渴爱与条件，不是给受苦者贴道德标签。社会、身体与关系条件也不能被一句“都是执著”草率抹掉。",
    },
    {
      myth: "灭谛就是让自己什么都没有、什么都不做",
      correction: "SN 56.11 把灭落在渴爱的离贪、止息、放下与解脱，又另列需要修习的八支圣道；这不是被动虚无，也不能用来回避现实责任。",
    },
  ],
  readingHeading: "先读任务，再读三转，然后回到条件与实践。",
  readingIntro: "这条路径让初学者不被名相淹没，也让研究者能直接核对汉巴段落和本站边界。",
  readingPath: [
    {
      step: "先抓住动作",
      title: "《杂阿含经》知苦、断集、证灭、修道",
      text: "先用一段最短原文分清四项任务，避免把四圣谛缩成“人生是苦”。",
      href: "/jingzang/zaahanjing/015-0104b#T0099.015.0104b15",
    },
    {
      step: "再看三转",
      title: "《杂阿含经》从当知当办到已经完成",
      text: "沿着认识、任务、完成三层阅读，核对“三转十二行”不是重复口号。",
      href: "/jingzang/zaahanjing/015-0103c#T0099.015.0103c14",
    },
    {
      step: "汉巴并读",
      title: "SN 56.11 的四谛界定与四项任务",
      text: "核对巴利原段怎样从苦的范围读到八支圣道，并保留工作释义与原文之间的边界。",
      href: "/jingzang/samyutta-nikaya-sn56/011-sn56-11-0001-0060#sn56.11:4.1",
    },
    {
      step: "追问条件",
      title: "从四谛继续进入缘起",
      text: "用缘起页追问苦与集如何依条件生起、又如何因条件止息，不把集谛变成单一原因论。",
      href: "/gainian/yuanqi",
    },
  ],
  footerNote: "本页只综合 foxue.ai 当前受控的《杂阿含经》与巴利《相应部》样本。它不替学界裁决严格平行经关系，不替后世论典与宗派作完整教判，也不能替代医疗、心理危机支持或具资质的现实帮助。",
  updatedAt: "2026-09-15",
  footerActionLabel: "带着任务继续问",
  footerActionHref: "/wenjing",
  related: ["bazhengdao", "yuanqi", "guanxin", "wuchang", "wuwo"],
} as const satisfies ConceptHub;
