// Generated by scripts/build-corpus-work-catalog.mjs. Do not edit.
export async function loadWorkCatalogShardWorks(id: number): Promise<Record<string, unknown> | null> {
  switch (id) {
    case 0:
      return ((await import("@/data/corpus-work-catalog-chunks/0.json")).default).works;
    case 1:
      return ((await import("@/data/corpus-work-catalog-chunks/1.json")).default).works;
    case 2:
      return ((await import("@/data/corpus-work-catalog-chunks/2.json")).default).works;
    case 3:
      return ((await import("@/data/corpus-work-catalog-chunks/3.json")).default).works;
    case 4:
      return ((await import("@/data/corpus-work-catalog-chunks/4.json")).default).works;
    case 5:
      return ((await import("@/data/corpus-work-catalog-chunks/5.json")).default).works;
    case 6:
      return ((await import("@/data/corpus-work-catalog-chunks/6.json")).default).works;
    case 7:
      return ((await import("@/data/corpus-work-catalog-chunks/7.json")).default).works;
    case 8:
      return ((await import("@/data/corpus-work-catalog-chunks/8.json")).default).works;
    case 9:
      return ((await import("@/data/corpus-work-catalog-chunks/9.json")).default).works;
    case 10:
      return ((await import("@/data/corpus-work-catalog-chunks/10.json")).default).works;
    case 11:
      return ((await import("@/data/corpus-work-catalog-chunks/11.json")).default).works;
    case 12:
      return ((await import("@/data/corpus-work-catalog-chunks/12.json")).default).works;
    case 13:
      return ((await import("@/data/corpus-work-catalog-chunks/13.json")).default).works;
    case 14:
      return ((await import("@/data/corpus-work-catalog-chunks/14.json")).default).works;
    case 15:
      return ((await import("@/data/corpus-work-catalog-chunks/15.json")).default).works;
    case 16:
      return ((await import("@/data/corpus-work-catalog-chunks/16.json")).default).works;
    case 17:
      return ((await import("@/data/corpus-work-catalog-chunks/17.json")).default).works;
    case 18:
      return ((await import("@/data/corpus-work-catalog-chunks/18.json")).default).works;
    case 19:
      return ((await import("@/data/corpus-work-catalog-chunks/19.json")).default).works;
    case 20:
      return ((await import("@/data/corpus-work-catalog-chunks/20.json")).default).works;
    case 21:
      return ((await import("@/data/corpus-work-catalog-chunks/21.json")).default).works;
    case 22:
      return ((await import("@/data/corpus-work-catalog-chunks/22.json")).default).works;
    case 23:
      return ((await import("@/data/corpus-work-catalog-chunks/23.json")).default).works;
    case 24:
      return ((await import("@/data/corpus-work-catalog-chunks/24.json")).default).works;
    case 25:
      return ((await import("@/data/corpus-work-catalog-chunks/25.json")).default).works;
    case 26:
      return ((await import("@/data/corpus-work-catalog-chunks/26.json")).default).works;
    case 27:
      return ((await import("@/data/corpus-work-catalog-chunks/27.json")).default).works;
    case 28:
      return ((await import("@/data/corpus-work-catalog-chunks/28.json")).default).works;
    case 29:
      return ((await import("@/data/corpus-work-catalog-chunks/29.json")).default).works;
    case 30:
      return ((await import("@/data/corpus-work-catalog-chunks/30.json")).default).works;
    case 31:
      return ((await import("@/data/corpus-work-catalog-chunks/31.json")).default).works;
    case 32:
      return ((await import("@/data/corpus-work-catalog-chunks/32.json")).default).works;
    case 33:
      return ((await import("@/data/corpus-work-catalog-chunks/33.json")).default).works;
    case 34:
      return ((await import("@/data/corpus-work-catalog-chunks/34.json")).default).works;
    case 35:
      return ((await import("@/data/corpus-work-catalog-chunks/35.json")).default).works;
    case 36:
      return ((await import("@/data/corpus-work-catalog-chunks/36.json")).default).works;
    case 37:
      return ((await import("@/data/corpus-work-catalog-chunks/37.json")).default).works;
    case 38:
      return ((await import("@/data/corpus-work-catalog-chunks/38.json")).default).works;
    case 39:
      return ((await import("@/data/corpus-work-catalog-chunks/39.json")).default).works;
    case 40:
      return ((await import("@/data/corpus-work-catalog-chunks/40.json")).default).works;
    case 41:
      return ((await import("@/data/corpus-work-catalog-chunks/41.json")).default).works;
    case 42:
      return ((await import("@/data/corpus-work-catalog-chunks/42.json")).default).works;
    case 43:
      return ((await import("@/data/corpus-work-catalog-chunks/43.json")).default).works;
    case 44:
      return ((await import("@/data/corpus-work-catalog-chunks/44.json")).default).works;
    case 45:
      return ((await import("@/data/corpus-work-catalog-chunks/45.json")).default).works;
    case 46:
      return ((await import("@/data/corpus-work-catalog-chunks/46.json")).default).works;
    case 47:
      return ((await import("@/data/corpus-work-catalog-chunks/47.json")).default).works;
    case 48:
      return ((await import("@/data/corpus-work-catalog-chunks/48.json")).default).works;
    case 49:
      return ((await import("@/data/corpus-work-catalog-chunks/49.json")).default).works;
    case 50:
      return ((await import("@/data/corpus-work-catalog-chunks/50.json")).default).works;
    case 51:
      return ((await import("@/data/corpus-work-catalog-chunks/51.json")).default).works;
    case 52:
      return ((await import("@/data/corpus-work-catalog-chunks/52.json")).default).works;
    case 53:
      return ((await import("@/data/corpus-work-catalog-chunks/53.json")).default).works;
    case 54:
      return ((await import("@/data/corpus-work-catalog-chunks/54.json")).default).works;
    case 55:
      return ((await import("@/data/corpus-work-catalog-chunks/55.json")).default).works;
    case 56:
      return ((await import("@/data/corpus-work-catalog-chunks/56.json")).default).works;
    case 57:
      return ((await import("@/data/corpus-work-catalog-chunks/57.json")).default).works;
    case 58:
      return ((await import("@/data/corpus-work-catalog-chunks/58.json")).default).works;
    case 59:
      return ((await import("@/data/corpus-work-catalog-chunks/59.json")).default).works;
    case 60:
      return ((await import("@/data/corpus-work-catalog-chunks/60.json")).default).works;
    case 61:
      return ((await import("@/data/corpus-work-catalog-chunks/61.json")).default).works;
    case 62:
      return ((await import("@/data/corpus-work-catalog-chunks/62.json")).default).works;
    case 63:
      return ((await import("@/data/corpus-work-catalog-chunks/63.json")).default).works;
    case 64:
      return ((await import("@/data/corpus-work-catalog-chunks/64.json")).default).works;
    case 65:
      return ((await import("@/data/corpus-work-catalog-chunks/65.json")).default).works;
    case 66:
      return ((await import("@/data/corpus-work-catalog-chunks/66.json")).default).works;
    case 67:
      return ((await import("@/data/corpus-work-catalog-chunks/67.json")).default).works;
    case 68:
      return ((await import("@/data/corpus-work-catalog-chunks/68.json")).default).works;
    case 69:
      return ((await import("@/data/corpus-work-catalog-chunks/69.json")).default).works;
    case 70:
      return ((await import("@/data/corpus-work-catalog-chunks/70.json")).default).works;
    case 71:
      return ((await import("@/data/corpus-work-catalog-chunks/71.json")).default).works;
    case 72:
      return ((await import("@/data/corpus-work-catalog-chunks/72.json")).default).works;
    case 73:
      return ((await import("@/data/corpus-work-catalog-chunks/73.json")).default).works;
    case 74:
      return ((await import("@/data/corpus-work-catalog-chunks/74.json")).default).works;
    case 75:
      return ((await import("@/data/corpus-work-catalog-chunks/75.json")).default).works;
    case 76:
      return ((await import("@/data/corpus-work-catalog-chunks/76.json")).default).works;
    case 77:
      return ((await import("@/data/corpus-work-catalog-chunks/77.json")).default).works;
    case 78:
      return ((await import("@/data/corpus-work-catalog-chunks/78.json")).default).works;
    case 79:
      return ((await import("@/data/corpus-work-catalog-chunks/79.json")).default).works;
    case 80:
      return ((await import("@/data/corpus-work-catalog-chunks/80.json")).default).works;
    case 81:
      return ((await import("@/data/corpus-work-catalog-chunks/81.json")).default).works;
    case 82:
      return ((await import("@/data/corpus-work-catalog-chunks/82.json")).default).works;
    case 83:
      return ((await import("@/data/corpus-work-catalog-chunks/83.json")).default).works;
    case 84:
      return ((await import("@/data/corpus-work-catalog-chunks/84.json")).default).works;
    case 85:
      return ((await import("@/data/corpus-work-catalog-chunks/85.json")).default).works;
    case 86:
      return ((await import("@/data/corpus-work-catalog-chunks/86.json")).default).works;
    case 87:
      return ((await import("@/data/corpus-work-catalog-chunks/87.json")).default).works;
    case 88:
      return ((await import("@/data/corpus-work-catalog-chunks/88.json")).default).works;
    default:
      return null;
  }
}
