// Generated by scripts/build-corpus-folio-locator.mjs. Do not edit.
export async function loadFolioLocatorShardWorks(id: number): Promise<Record<string, unknown> | null> {
  switch (id) {
    case 0:
      return ((await import("@/data/corpus-folio-locator-chunks/0.json")).default).works;
    case 1:
      return ((await import("@/data/corpus-folio-locator-chunks/1.json")).default).works;
    case 2:
      return ((await import("@/data/corpus-folio-locator-chunks/2.json")).default).works;
    case 3:
      return ((await import("@/data/corpus-folio-locator-chunks/3.json")).default).works;
    case 4:
      return ((await import("@/data/corpus-folio-locator-chunks/4.json")).default).works;
    case 5:
      return ((await import("@/data/corpus-folio-locator-chunks/5.json")).default).works;
    case 6:
      return ((await import("@/data/corpus-folio-locator-chunks/6.json")).default).works;
    case 7:
      return ((await import("@/data/corpus-folio-locator-chunks/7.json")).default).works;
    case 8:
      return ((await import("@/data/corpus-folio-locator-chunks/8.json")).default).works;
    case 9:
      return ((await import("@/data/corpus-folio-locator-chunks/9.json")).default).works;
    case 10:
      return ((await import("@/data/corpus-folio-locator-chunks/10.json")).default).works;
    case 11:
      return ((await import("@/data/corpus-folio-locator-chunks/11.json")).default).works;
    case 12:
      return ((await import("@/data/corpus-folio-locator-chunks/12.json")).default).works;
    case 13:
      return ((await import("@/data/corpus-folio-locator-chunks/13.json")).default).works;
    case 14:
      return ((await import("@/data/corpus-folio-locator-chunks/14.json")).default).works;
    case 15:
      return ((await import("@/data/corpus-folio-locator-chunks/15.json")).default).works;
    case 16:
      return ((await import("@/data/corpus-folio-locator-chunks/16.json")).default).works;
    case 17:
      return ((await import("@/data/corpus-folio-locator-chunks/17.json")).default).works;
    case 18:
      return ((await import("@/data/corpus-folio-locator-chunks/18.json")).default).works;
    case 19:
      return ((await import("@/data/corpus-folio-locator-chunks/19.json")).default).works;
    case 20:
      return ((await import("@/data/corpus-folio-locator-chunks/20.json")).default).works;
    case 21:
      return ((await import("@/data/corpus-folio-locator-chunks/21.json")).default).works;
    case 22:
      return ((await import("@/data/corpus-folio-locator-chunks/22.json")).default).works;
    case 23:
      return ((await import("@/data/corpus-folio-locator-chunks/23.json")).default).works;
    case 24:
      return ((await import("@/data/corpus-folio-locator-chunks/24.json")).default).works;
    case 25:
      return ((await import("@/data/corpus-folio-locator-chunks/25.json")).default).works;
    case 26:
      return ((await import("@/data/corpus-folio-locator-chunks/26.json")).default).works;
    case 27:
      return ((await import("@/data/corpus-folio-locator-chunks/27.json")).default).works;
    case 28:
      return ((await import("@/data/corpus-folio-locator-chunks/28.json")).default).works;
    case 29:
      return ((await import("@/data/corpus-folio-locator-chunks/29.json")).default).works;
    default:
      return null;
  }
}
