// Generated by scripts/build-corpus-sitemap-ledger.mjs. Do not edit.
export async function loadSitemapChunkPaths(id: number): Promise<string[] | null> {
  switch (id) {
    case 0:
      return ((await import("@/data/corpus-sitemap-chunks/0.json")).default).paths;
    case 1:
      return ((await import("@/data/corpus-sitemap-chunks/1.json")).default).paths;
    case 2:
      return ((await import("@/data/corpus-sitemap-chunks/2.json")).default).paths;
    case 3:
      return ((await import("@/data/corpus-sitemap-chunks/3.json")).default).paths;
    case 4:
      return ((await import("@/data/corpus-sitemap-chunks/4.json")).default).paths;
    case 5:
      return ((await import("@/data/corpus-sitemap-chunks/5.json")).default).paths;
    case 6:
      return ((await import("@/data/corpus-sitemap-chunks/6.json")).default).paths;
    default:
      return null;
  }
}
