// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:39":
      return import("@/data/corpus-work-catalog-chunks/39.json");
    case "catalog:63":
      return import("@/data/corpus-work-catalog-chunks/63.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:68":
      return import("@/data/corpus-work-catalog-chunks/68.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:71":
      return import("@/data/corpus-work-catalog-chunks/71.json");
    case "catalog:72":
      return import("@/data/corpus-work-catalog-chunks/72.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    default:
      return null;
  }
}
