// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:44":
      return import("@/data/corpus-work-catalog-chunks/44.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    case "catalog:61":
      return import("@/data/corpus-work-catalog-chunks/61.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:67":
      return import("@/data/corpus-work-catalog-chunks/67.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    case "catalog:91":
      return import("@/data/corpus-work-catalog-chunks/91.json");
    default:
      return null;
  }
}
