// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:12":
      return import("@/data/corpus-folio-locator-chunks/12.json");
    case "catalog:32":
      return import("@/data/corpus-work-catalog-chunks/32.json");
    default:
      return null;
  }
}
