// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    default:
      return null;
  }
}
