// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    case "catalog:57":
      return import("@/data/corpus-work-catalog-chunks/57.json");
    case "catalog:60":
      return import("@/data/corpus-work-catalog-chunks/60.json");
    case "catalog:61":
      return import("@/data/corpus-work-catalog-chunks/61.json");
    case "catalog:62":
      return import("@/data/corpus-work-catalog-chunks/62.json");
    case "catalog:64":
      return import("@/data/corpus-work-catalog-chunks/64.json");
    case "catalog:65":
      return import("@/data/corpus-work-catalog-chunks/65.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:73":
      return import("@/data/corpus-work-catalog-chunks/73.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    default:
      return null;
  }
}
