// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "locator:30":
      return import("@/data/corpus-folio-locator-chunks/30.json");
    case "catalog:53":
      return import("@/data/corpus-work-catalog-chunks/53.json");
    case "catalog:78":
      return import("@/data/corpus-work-catalog-chunks/78.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    default:
      return null;
  }
}
