// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:18":
      return import("@/data/corpus-folio-locator-chunks/18.json");
    case "locator:21":
      return import("@/data/corpus-folio-locator-chunks/21.json");
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:42":
      return import("@/data/corpus-work-catalog-chunks/42.json");
    case "catalog:48":
      return import("@/data/corpus-work-catalog-chunks/48.json");
    case "catalog:57":
      return import("@/data/corpus-work-catalog-chunks/57.json");
    case "catalog:58":
      return import("@/data/corpus-work-catalog-chunks/58.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    default:
      return null;
  }
}
