// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:18":
      return import("@/data/corpus-folio-locator-chunks/18.json");
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "locator:21":
      return import("@/data/corpus-folio-locator-chunks/21.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:29":
      return import("@/data/corpus-work-catalog-chunks/29.json");
    case "catalog:42":
      return import("@/data/corpus-work-catalog-chunks/42.json");
    case "catalog:53":
      return import("@/data/corpus-work-catalog-chunks/53.json");
    case "catalog:56":
      return import("@/data/corpus-work-catalog-chunks/56.json");
    case "catalog:61":
      return import("@/data/corpus-work-catalog-chunks/61.json");
    case "catalog:63":
      return import("@/data/corpus-work-catalog-chunks/63.json");
    case "catalog:72":
      return import("@/data/corpus-work-catalog-chunks/72.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:78":
      return import("@/data/corpus-work-catalog-chunks/78.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    default:
      return null;
  }
}
