// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:14":
      return import("@/data/corpus-folio-locator-chunks/14.json");
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "catalog:34":
      return import("@/data/corpus-work-catalog-chunks/34.json");
    case "catalog:43":
      return import("@/data/corpus-work-catalog-chunks/43.json");
    default:
      return null;
  }
}
