// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:3":
      return import("@/data/corpus-folio-locator-chunks/3.json");
    case "catalog:9":
      return import("@/data/corpus-work-catalog-chunks/9.json");
    default:
      return null;
  }
}
