// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:38":
      return import("@/data/corpus-work-catalog-chunks/38.json");
    case "catalog:41":
      return import("@/data/corpus-work-catalog-chunks/41.json");
    case "catalog:60":
      return import("@/data/corpus-work-catalog-chunks/60.json");
    case "catalog:63":
      return import("@/data/corpus-work-catalog-chunks/63.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    default:
      return null;
  }
}
