// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:13":
      return import("@/data/corpus-folio-locator-chunks/13.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "catalog:32":
      return import("@/data/corpus-work-catalog-chunks/32.json");
    case "catalog:72":
      return import("@/data/corpus-work-catalog-chunks/72.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    default:
      return null;
  }
}
