// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:41":
      return import("@/data/corpus-work-catalog-chunks/41.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    case "catalog:91":
      return import("@/data/corpus-work-catalog-chunks/91.json");
    default:
      return null;
  }
}
