// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:6":
      return import("@/data/corpus-folio-locator-chunks/6.json");
    case "catalog:14":
      return import("@/data/corpus-work-catalog-chunks/14.json");
    default:
      return null;
  }
}
