// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:14":
      return import("@/data/corpus-folio-locator-chunks/14.json");
    case "locator:15":
      return import("@/data/corpus-folio-locator-chunks/15.json");
    case "locator:21":
      return import("@/data/corpus-folio-locator-chunks/21.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:38":
      return import("@/data/corpus-work-catalog-chunks/38.json");
    case "catalog:40":
      return import("@/data/corpus-work-catalog-chunks/40.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    case "catalog:78":
      return import("@/data/corpus-work-catalog-chunks/78.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    default:
      return null;
  }
}
