// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "locator:30":
      return import("@/data/corpus-folio-locator-chunks/30.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:51":
      return import("@/data/corpus-work-catalog-chunks/51.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:73":
      return import("@/data/corpus-work-catalog-chunks/73.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    default:
      return null;
  }
}
