// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:8":
      return import("@/data/corpus-folio-locator-chunks/8.json");
    case "catalog:20":
      return import("@/data/corpus-work-catalog-chunks/20.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    default:
      return null;
  }
}
