// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "catalog:44":
      return import("@/data/corpus-work-catalog-chunks/44.json");
    case "catalog:57":
      return import("@/data/corpus-work-catalog-chunks/57.json");
    case "catalog:59":
      return import("@/data/corpus-work-catalog-chunks/59.json");
    case "catalog:62":
      return import("@/data/corpus-work-catalog-chunks/62.json");
    case "catalog:63":
      return import("@/data/corpus-work-catalog-chunks/63.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    default:
      return null;
  }
}
