// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:19":
      return import("@/data/corpus-folio-locator-chunks/19.json");
    case "catalog:50":
      return import("@/data/corpus-work-catalog-chunks/50.json");
    default:
      return null;
  }
}
