// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:15":
      return import("@/data/corpus-folio-locator-chunks/15.json");
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:18":
      return import("@/data/corpus-folio-locator-chunks/18.json");
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "catalog:37":
      return import("@/data/corpus-work-catalog-chunks/37.json");
    case "catalog:44":
      return import("@/data/corpus-work-catalog-chunks/44.json");
    case "catalog:47":
      return import("@/data/corpus-work-catalog-chunks/47.json");
    case "catalog:52":
      return import("@/data/corpus-work-catalog-chunks/52.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    default:
      return null;
  }
}
