// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:1":
      return import("@/data/corpus-folio-locator-chunks/1.json");
    case "catalog:0":
      return import("@/data/corpus-work-catalog-chunks/0.json");
    default:
      return null;
  }
}
