// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "catalog:47":
      return import("@/data/corpus-work-catalog-chunks/47.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    case "catalog:65":
      return import("@/data/corpus-work-catalog-chunks/65.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:69":
      return import("@/data/corpus-work-catalog-chunks/69.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    default:
      return null;
  }
}
