// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:13":
      return import("@/data/corpus-folio-locator-chunks/13.json");
    case "locator:14":
      return import("@/data/corpus-folio-locator-chunks/14.json");
    case "catalog:33":
      return import("@/data/corpus-work-catalog-chunks/33.json");
    case "catalog:36":
      return import("@/data/corpus-work-catalog-chunks/36.json");
    default:
      return null;
  }
}
