// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:18":
      return import("@/data/corpus-folio-locator-chunks/18.json");
    case "locator:19":
      return import("@/data/corpus-folio-locator-chunks/19.json");
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "locator:21":
      return import("@/data/corpus-folio-locator-chunks/21.json");
    case "catalog:45":
      return import("@/data/corpus-work-catalog-chunks/45.json");
    case "catalog:47":
      return import("@/data/corpus-work-catalog-chunks/47.json");
    case "catalog:48":
      return import("@/data/corpus-work-catalog-chunks/48.json");
    case "catalog:49":
      return import("@/data/corpus-work-catalog-chunks/49.json");
    case "catalog:50":
      return import("@/data/corpus-work-catalog-chunks/50.json");
    case "catalog:51":
      return import("@/data/corpus-work-catalog-chunks/51.json");
    case "catalog:52":
      return import("@/data/corpus-work-catalog-chunks/52.json");
    case "catalog:53":
      return import("@/data/corpus-work-catalog-chunks/53.json");
    case "catalog:54":
      return import("@/data/corpus-work-catalog-chunks/54.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    default:
      return null;
  }
}
