// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:15":
      return import("@/data/corpus-folio-locator-chunks/15.json");
    case "locator:18":
      return import("@/data/corpus-folio-locator-chunks/18.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "catalog:37":
      return import("@/data/corpus-work-catalog-chunks/37.json");
    case "catalog:45":
      return import("@/data/corpus-work-catalog-chunks/45.json");
    case "catalog:58":
      return import("@/data/corpus-work-catalog-chunks/58.json");
    case "catalog:61":
      return import("@/data/corpus-work-catalog-chunks/61.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    default:
      return null;
  }
}
