// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:14":
      return import("@/data/corpus-folio-locator-chunks/14.json");
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "catalog:37":
      return import("@/data/corpus-work-catalog-chunks/37.json");
    case "catalog:44":
      return import("@/data/corpus-work-catalog-chunks/44.json");
    case "catalog:57":
      return import("@/data/corpus-work-catalog-chunks/57.json");
    case "catalog:59":
      return import("@/data/corpus-work-catalog-chunks/59.json");
    case "catalog:64":
      return import("@/data/corpus-work-catalog-chunks/64.json");
    case "catalog:73":
      return import("@/data/corpus-work-catalog-chunks/73.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    default:
      return null;
  }
}
