// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    default:
      return null;
  }
}
