// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:8":
      return import("@/data/corpus-folio-locator-chunks/8.json");
    case "locator:15":
      return import("@/data/corpus-folio-locator-chunks/15.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "catalog:20":
      return import("@/data/corpus-work-catalog-chunks/20.json");
    case "catalog:37":
      return import("@/data/corpus-work-catalog-chunks/37.json");
    case "catalog:71":
      return import("@/data/corpus-work-catalog-chunks/71.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    default:
      return null;
  }
}
