// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:11":
      return import("@/data/corpus-folio-locator-chunks/11.json");
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:29":
      return import("@/data/corpus-work-catalog-chunks/29.json");
    case "catalog:45":
      return import("@/data/corpus-work-catalog-chunks/45.json");
    case "catalog:59":
      return import("@/data/corpus-work-catalog-chunks/59.json");
    case "catalog:71":
      return import("@/data/corpus-work-catalog-chunks/71.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    default:
      return null;
  }
}
