// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:7":
      return import("@/data/corpus-folio-locator-chunks/7.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "catalog:17":
      return import("@/data/corpus-work-catalog-chunks/17.json");
    case "catalog:64":
      return import("@/data/corpus-work-catalog-chunks/64.json");
    case "catalog:67":
      return import("@/data/corpus-work-catalog-chunks/67.json");
    case "catalog:72":
      return import("@/data/corpus-work-catalog-chunks/72.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    default:
      return null;
  }
}
