// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:7":
      return import("@/data/corpus-folio-locator-chunks/7.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "catalog:17":
      return import("@/data/corpus-work-catalog-chunks/17.json");
    case "catalog:63":
      return import("@/data/corpus-work-catalog-chunks/63.json");
    case "catalog:65":
      return import("@/data/corpus-work-catalog-chunks/65.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:74":
      return import("@/data/corpus-work-catalog-chunks/74.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    default:
      return null;
  }
}
