// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:20":
      return import("@/data/corpus-folio-locator-chunks/20.json");
    case "catalog:54":
      return import("@/data/corpus-work-catalog-chunks/54.json");
    default:
      return null;
  }
}
