// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:21":
      return import("@/data/corpus-folio-locator-chunks/21.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    default:
      return null;
  }
}
