// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:9":
      return import("@/data/corpus-folio-locator-chunks/9.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "catalog:18":
      return import("@/data/corpus-work-catalog-chunks/18.json");
    case "catalog:59":
      return import("@/data/corpus-work-catalog-chunks/59.json");
    default:
      return null;
  }
}
