// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:7":
      return import("@/data/corpus-folio-locator-chunks/7.json");
    case "catalog:13":
      return import("@/data/corpus-work-catalog-chunks/13.json");
    default:
      return null;
  }
}
