// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:4":
      return import("@/data/corpus-folio-locator-chunks/4.json");
    case "catalog:5":
      return import("@/data/corpus-work-catalog-chunks/5.json");
    default:
      return null;
  }
}
