// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:9":
      return import("@/data/corpus-folio-locator-chunks/9.json");
    case "catalog:24":
      return import("@/data/corpus-work-catalog-chunks/24.json");
    default:
      return null;
  }
}
