// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:22":
      return import("@/data/corpus-folio-locator-chunks/22.json");
    case "locator:25":
      return import("@/data/corpus-folio-locator-chunks/25.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "locator:30":
      return import("@/data/corpus-folio-locator-chunks/30.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:50":
      return import("@/data/corpus-work-catalog-chunks/50.json");
    case "catalog:51":
      return import("@/data/corpus-work-catalog-chunks/51.json");
    case "catalog:59":
      return import("@/data/corpus-work-catalog-chunks/59.json");
    case "catalog:62":
      return import("@/data/corpus-work-catalog-chunks/62.json");
    case "catalog:68":
      return import("@/data/corpus-work-catalog-chunks/68.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:73":
      return import("@/data/corpus-work-catalog-chunks/73.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:78":
      return import("@/data/corpus-work-catalog-chunks/78.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:91":
      return import("@/data/corpus-work-catalog-chunks/91.json");
    default:
      return null;
  }
}
