// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:17":
      return import("@/data/corpus-folio-locator-chunks/17.json");
    case "catalog:43":
      return import("@/data/corpus-work-catalog-chunks/43.json");
    case "catalog:44":
      return import("@/data/corpus-work-catalog-chunks/44.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    default:
      return null;
  }
}
