// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "locator:30":
      return import("@/data/corpus-folio-locator-chunks/30.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:35":
      return import("@/data/corpus-work-catalog-chunks/35.json");
    case "catalog:55":
      return import("@/data/corpus-work-catalog-chunks/55.json");
    case "catalog:56":
      return import("@/data/corpus-work-catalog-chunks/56.json");
    case "catalog:71":
      return import("@/data/corpus-work-catalog-chunks/71.json");
    case "catalog:72":
      return import("@/data/corpus-work-catalog-chunks/72.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    case "catalog:86":
      return import("@/data/corpus-work-catalog-chunks/86.json");
    case "catalog:87":
      return import("@/data/corpus-work-catalog-chunks/87.json");
    case "catalog:88":
      return import("@/data/corpus-work-catalog-chunks/88.json");
    case "catalog:89":
      return import("@/data/corpus-work-catalog-chunks/89.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    default:
      return null;
  }
}
