// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:15":
      return import("@/data/corpus-folio-locator-chunks/15.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:39":
      return import("@/data/corpus-work-catalog-chunks/39.json");
    case "catalog:60":
      return import("@/data/corpus-work-catalog-chunks/60.json");
    case "catalog:66":
      return import("@/data/corpus-work-catalog-chunks/66.json");
    case "catalog:69":
      return import("@/data/corpus-work-catalog-chunks/69.json");
    case "catalog:71":
      return import("@/data/corpus-work-catalog-chunks/71.json");
    case "catalog:73":
      return import("@/data/corpus-work-catalog-chunks/73.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:84":
      return import("@/data/corpus-work-catalog-chunks/84.json");
    case "catalog:85":
      return import("@/data/corpus-work-catalog-chunks/85.json");
    default:
      return null;
  }
}
