// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:2":
      return import("@/data/corpus-folio-locator-chunks/2.json");
    case "locator:10":
      return import("@/data/corpus-folio-locator-chunks/10.json");
    case "locator:29":
      return import("@/data/corpus-folio-locator-chunks/29.json");
    case "catalog:8":
      return import("@/data/corpus-work-catalog-chunks/8.json");
    case "catalog:27":
      return import("@/data/corpus-work-catalog-chunks/27.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    default:
      return null;
  }
}
