// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:16":
      return import("@/data/corpus-folio-locator-chunks/16.json");
    case "locator:23":
      return import("@/data/corpus-folio-locator-chunks/23.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "catalog:41":
      return import("@/data/corpus-work-catalog-chunks/41.json");
    case "catalog:42":
      return import("@/data/corpus-work-catalog-chunks/42.json");
    case "catalog:60":
      return import("@/data/corpus-work-catalog-chunks/60.json");
    case "catalog:70":
      return import("@/data/corpus-work-catalog-chunks/70.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    default:
      return null;
  }
}
