// Generated by scripts/build-corpus-runtime-buckets.mjs. Do not edit.
export async function includeCorpusBucketJson(kind: string): Promise<unknown> {
  switch (kind) {
    case "locator:24":
      return import("@/data/corpus-folio-locator-chunks/24.json");
    case "locator:26":
      return import("@/data/corpus-folio-locator-chunks/26.json");
    case "locator:27":
      return import("@/data/corpus-folio-locator-chunks/27.json");
    case "locator:28":
      return import("@/data/corpus-folio-locator-chunks/28.json");
    case "locator:30":
      return import("@/data/corpus-folio-locator-chunks/30.json");
    case "locator:31":
      return import("@/data/corpus-folio-locator-chunks/31.json");
    case "catalog:56":
      return import("@/data/corpus-work-catalog-chunks/56.json");
    case "catalog:58":
      return import("@/data/corpus-work-catalog-chunks/58.json");
    case "catalog:64":
      return import("@/data/corpus-work-catalog-chunks/64.json");
    case "catalog:65":
      return import("@/data/corpus-work-catalog-chunks/65.json");
    case "catalog:69":
      return import("@/data/corpus-work-catalog-chunks/69.json");
    case "catalog:75":
      return import("@/data/corpus-work-catalog-chunks/75.json");
    case "catalog:76":
      return import("@/data/corpus-work-catalog-chunks/76.json");
    case "catalog:77":
      return import("@/data/corpus-work-catalog-chunks/77.json");
    case "catalog:79":
      return import("@/data/corpus-work-catalog-chunks/79.json");
    case "catalog:80":
      return import("@/data/corpus-work-catalog-chunks/80.json");
    case "catalog:81":
      return import("@/data/corpus-work-catalog-chunks/81.json");
    case "catalog:82":
      return import("@/data/corpus-work-catalog-chunks/82.json");
    case "catalog:83":
      return import("@/data/corpus-work-catalog-chunks/83.json");
    case "catalog:90":
      return import("@/data/corpus-work-catalog-chunks/90.json");
    default:
      return null;
  }
}
